// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: github.com/dogmatiq/enginekit/internal/stubs/stubs.proto

package stubs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoStubA struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value string                 `protobuf:"bytes,1,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProtoStubA) Reset() {
	*x = ProtoStubA{}
	mi := &file_github_com_dogmatiq_enginekit_internal_stubs_stubs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoStubA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoStubA) ProtoMessage() {}

func (x *ProtoStubA) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_internal_stubs_stubs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProtoStubA) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *ProtoStubA) SetValue(v string) {
	x.xxx_hidden_Value = v
}

type ProtoStubA_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value string
}

func (b0 ProtoStubA_builder) Build() *ProtoStubA {
	m0 := &ProtoStubA{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	return m0
}

type ProtoStubB struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value string                 `protobuf:"bytes,1,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProtoStubB) Reset() {
	*x = ProtoStubB{}
	mi := &file_github_com_dogmatiq_enginekit_internal_stubs_stubs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoStubB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoStubB) ProtoMessage() {}

func (x *ProtoStubB) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_internal_stubs_stubs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProtoStubB) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *ProtoStubB) SetValue(v string) {
	x.xxx_hidden_Value = v
}

type ProtoStubB_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value string
}

func (b0 ProtoStubB_builder) Build() *ProtoStubB {
	m0 := &ProtoStubB{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	return m0
}

type ProtoStubC struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value string                 `protobuf:"bytes,1,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProtoStubC) Reset() {
	*x = ProtoStubC{}
	mi := &file_github_com_dogmatiq_enginekit_internal_stubs_stubs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoStubC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoStubC) ProtoMessage() {}

func (x *ProtoStubC) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_internal_stubs_stubs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProtoStubC) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *ProtoStubC) SetValue(v string) {
	x.xxx_hidden_Value = v
}

type ProtoStubC_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value string
}

func (b0 ProtoStubC_builder) Build() *ProtoStubC {
	m0 := &ProtoStubC{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	return m0
}

var File_github_com_dogmatiq_enginekit_internal_stubs_stubs_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_enginekit_internal_stubs_stubs_proto_rawDesc = "" +
	"\n" +
	"8github.com/dogmatiq/enginekit/internal/stubs/stubs.proto\x12\x18dogmatiq.enginekit.stubs\")\n" +
	"\n" +
	"ProtoStubA\x12\x1b\n" +
	"\x05value\x18\x01 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05value\")\n" +
	"\n" +
	"ProtoStubB\x12\x1b\n" +
	"\x05value\x18\x01 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05value\")\n" +
	"\n" +
	"ProtoStubC\x12\x1b\n" +
	"\x05value\x18\x01 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05valueB.Z,github.com/dogmatiq/enginekit/internal/stubsb\beditionsp\xe9\a"

var file_github_com_dogmatiq_enginekit_internal_stubs_stubs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_com_dogmatiq_enginekit_internal_stubs_stubs_proto_goTypes = []any{
	(*ProtoStubA)(nil), // 0: dogmatiq.enginekit.stubs.ProtoStubA
	(*ProtoStubB)(nil), // 1: dogmatiq.enginekit.stubs.ProtoStubB
	(*ProtoStubC)(nil), // 2: dogmatiq.enginekit.stubs.ProtoStubC
}
var file_github_com_dogmatiq_enginekit_internal_stubs_stubs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_enginekit_internal_stubs_stubs_proto_init() }
func file_github_com_dogmatiq_enginekit_internal_stubs_stubs_proto_init() {
	if File_github_com_dogmatiq_enginekit_internal_stubs_stubs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_enginekit_internal_stubs_stubs_proto_rawDesc), len(file_github_com_dogmatiq_enginekit_internal_stubs_stubs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_enginekit_internal_stubs_stubs_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_enginekit_internal_stubs_stubs_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_enginekit_internal_stubs_stubs_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_enginekit_internal_stubs_stubs_proto = out.File
	file_github_com_dogmatiq_enginekit_internal_stubs_stubs_proto_goTypes = nil
	file_github_com_dogmatiq_enginekit_internal_stubs_stubs_proto_depIdxs = nil
}
