// Code generated by protoc-gen-go-primo. DO NOT EDIT.
// versions:
// 	protoc-gen-go-primo v
// 	protoc              v6.33.1
// source: github.com/dogmatiq/enginekit/internal/stubs/stubs.proto

package stubs

import (
	"fmt"
	proto "google.golang.org/protobuf/proto"
)

type ProtoStubABuilder struct {
	prototype ProtoStubA
}

// NewProtoStubABuilder returns a builder that constructs [ProtoStubA] messages.
func NewProtoStubABuilder() *ProtoStubABuilder {
	return &ProtoStubABuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *ProtoStubABuilder) From(x *ProtoStubA) *ProtoStubABuilder {
	proto.Reset(&b.prototype)
	b.prototype.SetValue(x.GetValue())
	return b
}

// Build returns a new [ProtoStubA] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *ProtoStubABuilder) Build() *ProtoStubA {
	m := &ProtoStubA{}
	m.SetValue(b.prototype.GetValue())
	return m
}

// WithValue configures the builder to set the Value field to v,
// then returns b.
func (b *ProtoStubABuilder) WithValue(v string) *ProtoStubABuilder {
	b.prototype.SetValue(v)
	return b
}

type ProtoStubBBuilder struct {
	prototype ProtoStubB
}

// NewProtoStubBBuilder returns a builder that constructs [ProtoStubB] messages.
func NewProtoStubBBuilder() *ProtoStubBBuilder {
	return &ProtoStubBBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *ProtoStubBBuilder) From(x *ProtoStubB) *ProtoStubBBuilder {
	proto.Reset(&b.prototype)
	b.prototype.SetValue(x.GetValue())
	return b
}

// Build returns a new [ProtoStubB] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *ProtoStubBBuilder) Build() *ProtoStubB {
	m := &ProtoStubB{}
	m.SetValue(b.prototype.GetValue())
	return m
}

// WithValue configures the builder to set the Value field to v,
// then returns b.
func (b *ProtoStubBBuilder) WithValue(v string) *ProtoStubBBuilder {
	b.prototype.SetValue(v)
	return b
}

type ProtoStubCBuilder struct {
	prototype ProtoStubC
}

// NewProtoStubCBuilder returns a builder that constructs [ProtoStubC] messages.
func NewProtoStubCBuilder() *ProtoStubCBuilder {
	return &ProtoStubCBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *ProtoStubCBuilder) From(x *ProtoStubC) *ProtoStubCBuilder {
	proto.Reset(&b.prototype)
	b.prototype.SetValue(x.GetValue())
	return b
}

// Build returns a new [ProtoStubC] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *ProtoStubCBuilder) Build() *ProtoStubC {
	m := &ProtoStubC{}
	m.SetValue(b.prototype.GetValue())
	return m
}

// WithValue configures the builder to set the Value field to v,
// then returns b.
func (b *ProtoStubCBuilder) WithValue(v string) *ProtoStubCBuilder {
	b.prototype.SetValue(v)
	return b
}

// Format formats x according to the given [fmt] verb.
//
// It implements [fmt.Formatter], taking precedence over the String() method
// generated by the Protocol Buffers compiler.
//
// For the %s and %q verbs it uses the string returned by x.AsString() if x
// provides such a method. For the %#v verb it uses the string returned by
// x.GoString() if x provides such a method. Otherwise it formats x as though this
// method were not defined.
//
// AsString() and GoString() are called even when x is nil, since some message
// types handle a nil receiver themselves. If either method panics, the panic is
// formatted the same way the fmt package formats a panicking String() method.
func (x *ProtoStubA) Format(f fmt.State, verb rune) {
	format := fmt.FormatString(f, verb)

	if verb == 's' || verb == 'q' {
		if s, ok := any(x).(interface {
			AsString() string
		}); ok {
			result, ok := func() (result string, ok bool) {
				defer func() {
					if r := recover(); r != nil {
						result = fmt.Sprintf("%%!%c(PANIC=AsString method: %v)", verb, r)
					}
				}()
				return s.AsString(), true
			}()
			if ok {
				fmt.Fprintf(f, format, result)
			} else if x == nil {
				fmt.Fprint(f, "<nil>")
			} else {
				fmt.Fprint(f, result)
			}
			return
		}
	}

	if verb == 'v' && f.Flag('#') {
		if s, ok := any(x).(interface {
			GoString() string
		}); ok {
			result, ok := func() (result string, ok bool) {
				defer func() {
					if r := recover(); r != nil {
						result = fmt.Sprintf("%%!%c(PANIC=GoString method: %v)", verb, r)
					}
				}()
				return s.GoString(), true
			}()
			if ok {
				fmt.Fprintf(f, fmt.FormatString(f, 's'), result)
			} else if x == nil {
				fmt.Fprint(f, "<nil>")
			} else {
				fmt.Fprint(f, result)
			}
			return
		}
	} else {
		switch verb {
		case 'v', 's', 'x', 'X', 'q':
			fmt.Fprintf(f, format, x.String())
			return
		}
	}

	type realType = ProtoStubA
	type ProtoStubA realType
	fmt.Fprintf(f, format, (*ProtoStubA)(x))
}

// Format formats x according to the given [fmt] verb.
//
// It implements [fmt.Formatter], taking precedence over the String() method
// generated by the Protocol Buffers compiler.
//
// For the %s and %q verbs it uses the string returned by x.AsString() if x
// provides such a method. For the %#v verb it uses the string returned by
// x.GoString() if x provides such a method. Otherwise it formats x as though this
// method were not defined.
//
// AsString() and GoString() are called even when x is nil, since some message
// types handle a nil receiver themselves. If either method panics, the panic is
// formatted the same way the fmt package formats a panicking String() method.
func (x *ProtoStubB) Format(f fmt.State, verb rune) {
	format := fmt.FormatString(f, verb)

	if verb == 's' || verb == 'q' {
		if s, ok := any(x).(interface {
			AsString() string
		}); ok {
			result, ok := func() (result string, ok bool) {
				defer func() {
					if r := recover(); r != nil {
						result = fmt.Sprintf("%%!%c(PANIC=AsString method: %v)", verb, r)
					}
				}()
				return s.AsString(), true
			}()
			if ok {
				fmt.Fprintf(f, format, result)
			} else if x == nil {
				fmt.Fprint(f, "<nil>")
			} else {
				fmt.Fprint(f, result)
			}
			return
		}
	}

	if verb == 'v' && f.Flag('#') {
		if s, ok := any(x).(interface {
			GoString() string
		}); ok {
			result, ok := func() (result string, ok bool) {
				defer func() {
					if r := recover(); r != nil {
						result = fmt.Sprintf("%%!%c(PANIC=GoString method: %v)", verb, r)
					}
				}()
				return s.GoString(), true
			}()
			if ok {
				fmt.Fprintf(f, fmt.FormatString(f, 's'), result)
			} else if x == nil {
				fmt.Fprint(f, "<nil>")
			} else {
				fmt.Fprint(f, result)
			}
			return
		}
	} else {
		switch verb {
		case 'v', 's', 'x', 'X', 'q':
			fmt.Fprintf(f, format, x.String())
			return
		}
	}

	type realType = ProtoStubB
	type ProtoStubB realType
	fmt.Fprintf(f, format, (*ProtoStubB)(x))
}

// Format formats x according to the given [fmt] verb.
//
// It implements [fmt.Formatter], taking precedence over the String() method
// generated by the Protocol Buffers compiler.
//
// For the %s and %q verbs it uses the string returned by x.AsString() if x
// provides such a method. For the %#v verb it uses the string returned by
// x.GoString() if x provides such a method. Otherwise it formats x as though this
// method were not defined.
//
// AsString() and GoString() are called even when x is nil, since some message
// types handle a nil receiver themselves. If either method panics, the panic is
// formatted the same way the fmt package formats a panicking String() method.
func (x *ProtoStubC) Format(f fmt.State, verb rune) {
	format := fmt.FormatString(f, verb)

	if verb == 's' || verb == 'q' {
		if s, ok := any(x).(interface {
			AsString() string
		}); ok {
			result, ok := func() (result string, ok bool) {
				defer func() {
					if r := recover(); r != nil {
						result = fmt.Sprintf("%%!%c(PANIC=AsString method: %v)", verb, r)
					}
				}()
				return s.AsString(), true
			}()
			if ok {
				fmt.Fprintf(f, format, result)
			} else if x == nil {
				fmt.Fprint(f, "<nil>")
			} else {
				fmt.Fprint(f, result)
			}
			return
		}
	}

	if verb == 'v' && f.Flag('#') {
		if s, ok := any(x).(interface {
			GoString() string
		}); ok {
			result, ok := func() (result string, ok bool) {
				defer func() {
					if r := recover(); r != nil {
						result = fmt.Sprintf("%%!%c(PANIC=GoString method: %v)", verb, r)
					}
				}()
				return s.GoString(), true
			}()
			if ok {
				fmt.Fprintf(f, fmt.FormatString(f, 's'), result)
			} else if x == nil {
				fmt.Fprint(f, "<nil>")
			} else {
				fmt.Fprint(f, result)
			}
			return
		}
	} else {
		switch verb {
		case 'v', 's', 'x', 'X', 'q':
			fmt.Fprintf(f, format, x.String())
			return
		}
	}

	type realType = ProtoStubC
	type ProtoStubC realType
	fmt.Fprintf(f, format, (*ProtoStubC)(x))
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*ProtoStubA] to implement [encoding.BinaryMarshaler].
func (x *ProtoStubA) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*ProtoStubA] to implement [encoding.BinaryUnmarshaler].
func (x *ProtoStubA) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*ProtoStubB] to implement [encoding.BinaryMarshaler].
func (x *ProtoStubB) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*ProtoStubB] to implement [encoding.BinaryUnmarshaler].
func (x *ProtoStubB) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*ProtoStubC] to implement [encoding.BinaryMarshaler].
func (x *ProtoStubC) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*ProtoStubC] to implement [encoding.BinaryUnmarshaler].
func (x *ProtoStubC) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}
