// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: github.com/dogmatiq/enginekit/enginetest/internal/action/action.proto

package action

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Behavior isAction_Behavior      `protobuf_oneof:"behavior"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Action) GetFail() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Behavior.(*action_Fail); ok {
			return x.Fail
		}
	}
	return ""
}

func (x *Action) GetLog() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Behavior.(*action_Log); ok {
			return x.Log
		}
	}
	return ""
}

func (x *Action) GetExecuteCommand() *anypb.Any {
	if x != nil {
		if x, ok := x.xxx_hidden_Behavior.(*action_ExecuteCommand); ok {
			return x.ExecuteCommand
		}
	}
	return nil
}

func (x *Action) GetRecordEvent() *anypb.Any {
	if x != nil {
		if x, ok := x.xxx_hidden_Behavior.(*action_RecordEvent); ok {
			return x.RecordEvent
		}
	}
	return nil
}

func (x *Action) GetScheduleTimeout() *ScheduleTimeoutDetails {
	if x != nil {
		if x, ok := x.xxx_hidden_Behavior.(*action_ScheduleTimeout); ok {
			return x.ScheduleTimeout
		}
	}
	return nil
}

func (x *Action) GetDestroy() *Empty {
	if x != nil {
		if x, ok := x.xxx_hidden_Behavior.(*action_Destroy); ok {
			return x.Destroy
		}
	}
	return nil
}

func (x *Action) GetEnd() *Empty {
	if x != nil {
		if x, ok := x.xxx_hidden_Behavior.(*action_End); ok {
			return x.End
		}
	}
	return nil
}

func (x *Action) SetFail(v string) {
	x.xxx_hidden_Behavior = &action_Fail{v}
}

func (x *Action) SetLog(v string) {
	x.xxx_hidden_Behavior = &action_Log{v}
}

func (x *Action) SetExecuteCommand(v *anypb.Any) {
	if v == nil {
		x.xxx_hidden_Behavior = nil
		return
	}
	x.xxx_hidden_Behavior = &action_ExecuteCommand{v}
}

func (x *Action) SetRecordEvent(v *anypb.Any) {
	if v == nil {
		x.xxx_hidden_Behavior = nil
		return
	}
	x.xxx_hidden_Behavior = &action_RecordEvent{v}
}

func (x *Action) SetScheduleTimeout(v *ScheduleTimeoutDetails) {
	if v == nil {
		x.xxx_hidden_Behavior = nil
		return
	}
	x.xxx_hidden_Behavior = &action_ScheduleTimeout{v}
}

func (x *Action) SetDestroy(v *Empty) {
	if v == nil {
		x.xxx_hidden_Behavior = nil
		return
	}
	x.xxx_hidden_Behavior = &action_Destroy{v}
}

func (x *Action) SetEnd(v *Empty) {
	if v == nil {
		x.xxx_hidden_Behavior = nil
		return
	}
	x.xxx_hidden_Behavior = &action_End{v}
}

func (x *Action) HasBehavior() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Behavior != nil
}

func (x *Action) HasFail() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Behavior.(*action_Fail)
	return ok
}

func (x *Action) HasLog() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Behavior.(*action_Log)
	return ok
}

func (x *Action) HasExecuteCommand() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Behavior.(*action_ExecuteCommand)
	return ok
}

func (x *Action) HasRecordEvent() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Behavior.(*action_RecordEvent)
	return ok
}

func (x *Action) HasScheduleTimeout() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Behavior.(*action_ScheduleTimeout)
	return ok
}

func (x *Action) HasDestroy() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Behavior.(*action_Destroy)
	return ok
}

func (x *Action) HasEnd() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Behavior.(*action_End)
	return ok
}

func (x *Action) ClearBehavior() {
	x.xxx_hidden_Behavior = nil
}

func (x *Action) ClearFail() {
	if _, ok := x.xxx_hidden_Behavior.(*action_Fail); ok {
		x.xxx_hidden_Behavior = nil
	}
}

func (x *Action) ClearLog() {
	if _, ok := x.xxx_hidden_Behavior.(*action_Log); ok {
		x.xxx_hidden_Behavior = nil
	}
}

func (x *Action) ClearExecuteCommand() {
	if _, ok := x.xxx_hidden_Behavior.(*action_ExecuteCommand); ok {
		x.xxx_hidden_Behavior = nil
	}
}

func (x *Action) ClearRecordEvent() {
	if _, ok := x.xxx_hidden_Behavior.(*action_RecordEvent); ok {
		x.xxx_hidden_Behavior = nil
	}
}

func (x *Action) ClearScheduleTimeout() {
	if _, ok := x.xxx_hidden_Behavior.(*action_ScheduleTimeout); ok {
		x.xxx_hidden_Behavior = nil
	}
}

func (x *Action) ClearDestroy() {
	if _, ok := x.xxx_hidden_Behavior.(*action_Destroy); ok {
		x.xxx_hidden_Behavior = nil
	}
}

func (x *Action) ClearEnd() {
	if _, ok := x.xxx_hidden_Behavior.(*action_End); ok {
		x.xxx_hidden_Behavior = nil
	}
}

const Action_Behavior_not_set_case case_Action_Behavior = 0
const Action_Fail_case case_Action_Behavior = 1
const Action_Log_case case_Action_Behavior = 2
const Action_ExecuteCommand_case case_Action_Behavior = 3
const Action_RecordEvent_case case_Action_Behavior = 4
const Action_ScheduleTimeout_case case_Action_Behavior = 5
const Action_Destroy_case case_Action_Behavior = 6
const Action_End_case case_Action_Behavior = 7

func (x *Action) WhichBehavior() case_Action_Behavior {
	if x == nil {
		return Action_Behavior_not_set_case
	}
	switch x.xxx_hidden_Behavior.(type) {
	case *action_Fail:
		return Action_Fail_case
	case *action_Log:
		return Action_Log_case
	case *action_ExecuteCommand:
		return Action_ExecuteCommand_case
	case *action_RecordEvent:
		return Action_RecordEvent_case
	case *action_ScheduleTimeout:
		return Action_ScheduleTimeout_case
	case *action_Destroy:
		return Action_Destroy_case
	case *action_End:
		return Action_End_case
	default:
		return Action_Behavior_not_set_case
	}
}

type Action_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Behavior:
	Fail            *string
	Log             *string
	ExecuteCommand  *anypb.Any
	RecordEvent     *anypb.Any
	ScheduleTimeout *ScheduleTimeoutDetails
	Destroy         *Empty
	End             *Empty
	// -- end of xxx_hidden_Behavior
}

func (b0 Action_builder) Build() *Action {
	m0 := &Action{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Fail != nil {
		x.xxx_hidden_Behavior = &action_Fail{*b.Fail}
	}
	if b.Log != nil {
		x.xxx_hidden_Behavior = &action_Log{*b.Log}
	}
	if b.ExecuteCommand != nil {
		x.xxx_hidden_Behavior = &action_ExecuteCommand{b.ExecuteCommand}
	}
	if b.RecordEvent != nil {
		x.xxx_hidden_Behavior = &action_RecordEvent{b.RecordEvent}
	}
	if b.ScheduleTimeout != nil {
		x.xxx_hidden_Behavior = &action_ScheduleTimeout{b.ScheduleTimeout}
	}
	if b.Destroy != nil {
		x.xxx_hidden_Behavior = &action_Destroy{b.Destroy}
	}
	if b.End != nil {
		x.xxx_hidden_Behavior = &action_End{b.End}
	}
	return m0
}

type case_Action_Behavior protoreflect.FieldNumber

func (x case_Action_Behavior) String() string {
	md := file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isAction_Behavior interface {
	isAction_Behavior()
}

type action_Fail struct {
	Fail string `protobuf:"bytes,1,opt,name=fail,oneof"`
}

type action_Log struct {
	Log string `protobuf:"bytes,2,opt,name=log,oneof"`
}

type action_ExecuteCommand struct {
	ExecuteCommand *anypb.Any `protobuf:"bytes,3,opt,name=execute_command,json=executeCommand,oneof"`
}

type action_RecordEvent struct {
	RecordEvent *anypb.Any `protobuf:"bytes,4,opt,name=record_event,json=recordEvent,oneof"`
}

type action_ScheduleTimeout struct {
	ScheduleTimeout *ScheduleTimeoutDetails `protobuf:"bytes,5,opt,name=schedule_timeout,json=scheduleTimeout,oneof"`
}

type action_Destroy struct {
	Destroy *Empty `protobuf:"bytes,6,opt,name=destroy,oneof"`
}

type action_End struct {
	End *Empty `protobuf:"bytes,7,opt,name=end,oneof"`
}

func (*action_Fail) isAction_Behavior() {}

func (*action_Log) isAction_Behavior() {}

func (*action_ExecuteCommand) isAction_Behavior() {}

func (*action_RecordEvent) isAction_Behavior() {}

func (*action_ScheduleTimeout) isAction_Behavior() {}

func (*action_Destroy) isAction_Behavior() {}

func (*action_End) isAction_Behavior() {}

type ScheduleTimeoutDetails struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Timeout *anypb.Any             `protobuf:"bytes,1,opt,name=timeout"`
	xxx_hidden_At      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=at"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ScheduleTimeoutDetails) Reset() {
	*x = ScheduleTimeoutDetails{}
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTimeoutDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTimeoutDetails) ProtoMessage() {}

func (x *ScheduleTimeoutDetails) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ScheduleTimeoutDetails) GetTimeout() *anypb.Any {
	if x != nil {
		return x.xxx_hidden_Timeout
	}
	return nil
}

func (x *ScheduleTimeoutDetails) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_At
	}
	return nil
}

func (x *ScheduleTimeoutDetails) SetTimeout(v *anypb.Any) {
	x.xxx_hidden_Timeout = v
}

func (x *ScheduleTimeoutDetails) SetAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_At = v
}

func (x *ScheduleTimeoutDetails) HasTimeout() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timeout != nil
}

func (x *ScheduleTimeoutDetails) HasAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_At != nil
}

func (x *ScheduleTimeoutDetails) ClearTimeout() {
	x.xxx_hidden_Timeout = nil
}

func (x *ScheduleTimeoutDetails) ClearAt() {
	x.xxx_hidden_At = nil
}

type ScheduleTimeoutDetails_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Timeout *anypb.Any
	At      *timestamppb.Timestamp
}

func (b0 ScheduleTimeoutDetails_builder) Build() *ScheduleTimeoutDetails {
	m0 := &ScheduleTimeoutDetails{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Timeout = b.Timeout
	x.xxx_hidden_At = b.At
	return m0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Empty_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Empty_builder) Build() *Empty {
	m0 := &Empty{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_rawDesc = "" +
	"\n" +
	"Egithub.com/dogmatiq/enginekit/enginetest/internal/action/action.proto\x12\x1ddogmatiq.enginekit.enginetest\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!google/protobuf/go_features.proto\"\x9a\x03\n" +
	"\x06Action\x12\x14\n" +
	"\x04fail\x18\x01 \x01(\tH\x00R\x04fail\x12\x12\n" +
	"\x03log\x18\x02 \x01(\tH\x00R\x03log\x12?\n" +
	"\x0fexecute_command\x18\x03 \x01(\v2\x14.google.protobuf.AnyH\x00R\x0eexecuteCommand\x129\n" +
	"\frecord_event\x18\x04 \x01(\v2\x14.google.protobuf.AnyH\x00R\vrecordEvent\x12b\n" +
	"\x10schedule_timeout\x18\x05 \x01(\v25.dogmatiq.enginekit.enginetest.ScheduleTimeoutDetailsH\x00R\x0fscheduleTimeout\x12@\n" +
	"\adestroy\x18\x06 \x01(\v2$.dogmatiq.enginekit.enginetest.EmptyH\x00R\adestroy\x128\n" +
	"\x03end\x18\a \x01(\v2$.dogmatiq.enginekit.enginetest.EmptyH\x00R\x03endB\n" +
	"\n" +
	"\bbehavior\"t\n" +
	"\x16ScheduleTimeoutDetails\x12.\n" +
	"\atimeout\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\atimeout\x12*\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"\a\n" +
	"\x05EmptyBBZ8github.com/dogmatiq/enginekit/enginetest/internal/action\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe9\a"

var file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_goTypes = []any{
	(*Action)(nil),                 // 0: dogmatiq.enginekit.enginetest.Action
	(*ScheduleTimeoutDetails)(nil), // 1: dogmatiq.enginekit.enginetest.ScheduleTimeoutDetails
	(*Empty)(nil),                  // 2: dogmatiq.enginekit.enginetest.Empty
	(*anypb.Any)(nil),              // 3: google.protobuf.Any
	(*timestamppb.Timestamp)(nil),  // 4: google.protobuf.Timestamp
}
var file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_depIdxs = []int32{
	3, // 0: dogmatiq.enginekit.enginetest.Action.execute_command:type_name -> google.protobuf.Any
	3, // 1: dogmatiq.enginekit.enginetest.Action.record_event:type_name -> google.protobuf.Any
	1, // 2: dogmatiq.enginekit.enginetest.Action.schedule_timeout:type_name -> dogmatiq.enginekit.enginetest.ScheduleTimeoutDetails
	2, // 3: dogmatiq.enginekit.enginetest.Action.destroy:type_name -> dogmatiq.enginekit.enginetest.Empty
	2, // 4: dogmatiq.enginekit.enginetest.Action.end:type_name -> dogmatiq.enginekit.enginetest.Empty
	3, // 5: dogmatiq.enginekit.enginetest.ScheduleTimeoutDetails.timeout:type_name -> google.protobuf.Any
	4, // 6: dogmatiq.enginekit.enginetest.ScheduleTimeoutDetails.at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_init() }
func file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_init() {
	if File_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto != nil {
		return
	}
	file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_msgTypes[0].OneofWrappers = []any{
		(*action_Fail)(nil),
		(*action_Log)(nil),
		(*action_ExecuteCommand)(nil),
		(*action_RecordEvent)(nil),
		(*action_ScheduleTimeout)(nil),
		(*action_Destroy)(nil),
		(*action_End)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_rawDesc), len(file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto = out.File
	file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_goTypes = nil
	file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_depIdxs = nil
}
