// Code generated by protoc-gen-go-primo. DO NOT EDIT.
// versions:
// 	protoc-gen-go-primo v
// 	protoc              v6.33.1
// source: github.com/dogmatiq/enginekit/enginetest/internal/action/action.proto

package action

import (
	proto "google.golang.org/protobuf/proto"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// TryGetFail returns the Fail value if x.Behavior is set to Fail.
// Otherwise, ok is false and v is the zero-value.
func (x *Action) TryGetFail() (v string, ok bool) {
	if x.HasFail() {
		return x.GetFail(), true
	}
	return v, false
}

// TryGetLog returns the Log value if x.Behavior is set to Log.
// Otherwise, ok is false and v is the zero-value.
func (x *Action) TryGetLog() (v string, ok bool) {
	if x.HasLog() {
		return x.GetLog(), true
	}
	return v, false
}

// TryGetExecuteCommand returns the ExecuteCommand value if x.Behavior is set to ExecuteCommand.
// Otherwise, ok is false and v is the zero-value.
func (x *Action) TryGetExecuteCommand() (v *anypb.Any, ok bool) {
	if x.HasExecuteCommand() {
		return x.GetExecuteCommand(), true
	}
	return v, false
}

// TryGetRecordEvent returns the RecordEvent value if x.Behavior is set to RecordEvent.
// Otherwise, ok is false and v is the zero-value.
func (x *Action) TryGetRecordEvent() (v *anypb.Any, ok bool) {
	if x.HasRecordEvent() {
		return x.GetRecordEvent(), true
	}
	return v, false
}

// TryGetScheduleTimeout returns the ScheduleTimeout value if x.Behavior is set to ScheduleTimeout.
// Otherwise, ok is false and v is the zero-value.
func (x *Action) TryGetScheduleTimeout() (v *ScheduleTimeoutDetails, ok bool) {
	if x.HasScheduleTimeout() {
		return x.GetScheduleTimeout(), true
	}
	return v, false
}

// TryGetDestroy returns the Destroy value if x.Behavior is set to Destroy.
// Otherwise, ok is false and v is the zero-value.
func (x *Action) TryGetDestroy() (v *Empty, ok bool) {
	if x.HasDestroy() {
		return x.GetDestroy(), true
	}
	return v, false
}

// TryGetEnd returns the End value if x.Behavior is set to End.
// Otherwise, ok is false and v is the zero-value.
func (x *Action) TryGetEnd() (v *Empty, ok bool) {
	if x.HasEnd() {
		return x.GetEnd(), true
	}
	return v, false
}

type ActionBuilder struct {
	prototype Action
}

// NewActionBuilder returns a builder that constructs [Action] messages.
func NewActionBuilder() *ActionBuilder {
	return &ActionBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *ActionBuilder) From(x *Action) *ActionBuilder {
	proto.Reset(&b.prototype)
	if x.HasFail() {
		b.prototype.SetFail(x.GetFail())
	}
	if x.HasLog() {
		b.prototype.SetLog(x.GetLog())
	}
	if x.HasExecuteCommand() {
		b.prototype.SetExecuteCommand(x.GetExecuteCommand())
	}
	if x.HasRecordEvent() {
		b.prototype.SetRecordEvent(x.GetRecordEvent())
	}
	if x.HasScheduleTimeout() {
		b.prototype.SetScheduleTimeout(x.GetScheduleTimeout())
	}
	if x.HasDestroy() {
		b.prototype.SetDestroy(x.GetDestroy())
	}
	if x.HasEnd() {
		b.prototype.SetEnd(x.GetEnd())
	}
	return b
}

// Build returns a new [Action] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *ActionBuilder) Build() *Action {
	m := &Action{}
	if b.prototype.HasFail() {
		m.SetFail(b.prototype.GetFail())
	}
	if b.prototype.HasLog() {
		m.SetLog(b.prototype.GetLog())
	}
	if b.prototype.HasExecuteCommand() {
		m.SetExecuteCommand(b.prototype.GetExecuteCommand())
	}
	if b.prototype.HasRecordEvent() {
		m.SetRecordEvent(b.prototype.GetRecordEvent())
	}
	if b.prototype.HasScheduleTimeout() {
		m.SetScheduleTimeout(b.prototype.GetScheduleTimeout())
	}
	if b.prototype.HasDestroy() {
		m.SetDestroy(b.prototype.GetDestroy())
	}
	if b.prototype.HasEnd() {
		m.SetEnd(b.prototype.GetEnd())
	}
	return m
}

// WithFail configures the builder to set the Fail field to v,
// then returns b.
func (b *ActionBuilder) WithFail(v string) *ActionBuilder {
	b.prototype.SetFail(v)
	return b
}

// WithLog configures the builder to set the Log field to v,
// then returns b.
func (b *ActionBuilder) WithLog(v string) *ActionBuilder {
	b.prototype.SetLog(v)
	return b
}

// WithExecuteCommand configures the builder to set the ExecuteCommand field to v,
// then returns b.
func (b *ActionBuilder) WithExecuteCommand(v *anypb.Any) *ActionBuilder {
	b.prototype.SetExecuteCommand(v)
	return b
}

// WithRecordEvent configures the builder to set the RecordEvent field to v,
// then returns b.
func (b *ActionBuilder) WithRecordEvent(v *anypb.Any) *ActionBuilder {
	b.prototype.SetRecordEvent(v)
	return b
}

// WithScheduleTimeout configures the builder to set the ScheduleTimeout field to v,
// then returns b.
func (b *ActionBuilder) WithScheduleTimeout(v *ScheduleTimeoutDetails) *ActionBuilder {
	b.prototype.SetScheduleTimeout(v)
	return b
}

// WithDestroy configures the builder to set the Destroy field to v,
// then returns b.
func (b *ActionBuilder) WithDestroy(v *Empty) *ActionBuilder {
	b.prototype.SetDestroy(v)
	return b
}

// WithEnd configures the builder to set the End field to v,
// then returns b.
func (b *ActionBuilder) WithEnd(v *Empty) *ActionBuilder {
	b.prototype.SetEnd(v)
	return b
}

type ScheduleTimeoutDetailsBuilder struct {
	prototype ScheduleTimeoutDetails
}

// NewScheduleTimeoutDetailsBuilder returns a builder that constructs [ScheduleTimeoutDetails] messages.
func NewScheduleTimeoutDetailsBuilder() *ScheduleTimeoutDetailsBuilder {
	return &ScheduleTimeoutDetailsBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *ScheduleTimeoutDetailsBuilder) From(x *ScheduleTimeoutDetails) *ScheduleTimeoutDetailsBuilder {
	proto.Reset(&b.prototype)
	if x.HasTimeout() {
		b.prototype.SetTimeout(x.GetTimeout())
	}
	if x.HasAt() {
		b.prototype.SetAt(x.GetAt())
	}
	return b
}

// Build returns a new [ScheduleTimeoutDetails] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *ScheduleTimeoutDetailsBuilder) Build() *ScheduleTimeoutDetails {
	m := &ScheduleTimeoutDetails{}
	if b.prototype.HasTimeout() {
		m.SetTimeout(b.prototype.GetTimeout())
	}
	if b.prototype.HasAt() {
		m.SetAt(b.prototype.GetAt())
	}
	return m
}

// WithTimeout configures the builder to set the Timeout field to v,
// then returns b.
func (b *ScheduleTimeoutDetailsBuilder) WithTimeout(v *anypb.Any) *ScheduleTimeoutDetailsBuilder {
	b.prototype.SetTimeout(v)
	return b
}

// WithAt configures the builder to set the At field to v,
// then returns b.
func (b *ScheduleTimeoutDetailsBuilder) WithAt(v *timestamppb.Timestamp) *ScheduleTimeoutDetailsBuilder {
	b.prototype.SetAt(v)
	return b
}

type EmptyBuilder struct {
	prototype Empty
}

// NewEmptyBuilder returns a builder that constructs [Empty] messages.
func NewEmptyBuilder() *EmptyBuilder {
	return &EmptyBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *EmptyBuilder) From(x *Empty) *EmptyBuilder {
	proto.Reset(&b.prototype)
	return b
}

// Build returns a new [Empty] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *EmptyBuilder) Build() *Empty {
	m := &Empty{}
	return m
}

// MustSwitch_Action_Behavior invokes one of the given functions based on
// the value of x.Behavior.
//
// It panics if x.Behavior is nil.
func MustSwitch_Action_Behavior(
	x *Action,
	caseFail func(string),
	caseLog func(string),
	caseExecuteCommand func(*anypb.Any),
	caseRecordEvent func(*anypb.Any),
	caseScheduleTimeout func(*ScheduleTimeoutDetails),
	caseDestroy func(*Empty),
	caseEnd func(*Empty),
) {
	switch x.WhichBehavior() {
	case Action_Fail_case:
		caseFail(x.GetFail())
	case Action_Log_case:
		caseLog(x.GetLog())
	case Action_ExecuteCommand_case:
		caseExecuteCommand(x.GetExecuteCommand())
	case Action_RecordEvent_case:
		caseRecordEvent(x.GetRecordEvent())
	case Action_ScheduleTimeout_case:
		caseScheduleTimeout(x.GetScheduleTimeout())
	case Action_Destroy_case:
		caseDestroy(x.GetDestroy())
	case Action_End_case:
		caseEnd(x.GetEnd())
	default:
		panic("MustSwitch_Action_Behavior: x.Behavior is not set")
	}
}

// Switch_Action_Behavior invokes one of the given functions based on
// the value of x.Behavior.
//
// It calls none() if x.Behavior is nil.
func Switch_Action_Behavior(
	x *Action,
	caseFail func(string),
	caseLog func(string),
	caseExecuteCommand func(*anypb.Any),
	caseRecordEvent func(*anypb.Any),
	caseScheduleTimeout func(*ScheduleTimeoutDetails),
	caseDestroy func(*Empty),
	caseEnd func(*Empty),
	none func(),
) {
	switch x.WhichBehavior() {
	case Action_Fail_case:
		caseFail(x.GetFail())
	case Action_Log_case:
		caseLog(x.GetLog())
	case Action_ExecuteCommand_case:
		caseExecuteCommand(x.GetExecuteCommand())
	case Action_RecordEvent_case:
		caseRecordEvent(x.GetRecordEvent())
	case Action_ScheduleTimeout_case:
		caseScheduleTimeout(x.GetScheduleTimeout())
	case Action_Destroy_case:
		caseDestroy(x.GetDestroy())
	case Action_End_case:
		caseEnd(x.GetEnd())
	default:
		none()
	}
}

// MustMap_Action_Behavior maps x.Behavior to a value of type T by invoking
// one of the given functions.
//
// It invokes the function that corresponds to the value of x.Behavior,
// and returns that function's result. It panics if x.Behavior is nil.
func MustMap_Action_Behavior[T any](
	x *Action,
	caseFail func(string) T,
	caseLog func(string) T,
	caseExecuteCommand func(*anypb.Any) T,
	caseRecordEvent func(*anypb.Any) T,
	caseScheduleTimeout func(*ScheduleTimeoutDetails) T,
	caseDestroy func(*Empty) T,
	caseEnd func(*Empty) T,
) T {
	switch x.WhichBehavior() {
	case Action_Fail_case:
		return caseFail(x.GetFail())
	case Action_Log_case:
		return caseLog(x.GetLog())
	case Action_ExecuteCommand_case:
		return caseExecuteCommand(x.GetExecuteCommand())
	case Action_RecordEvent_case:
		return caseRecordEvent(x.GetRecordEvent())
	case Action_ScheduleTimeout_case:
		return caseScheduleTimeout(x.GetScheduleTimeout())
	case Action_Destroy_case:
		return caseDestroy(x.GetDestroy())
	case Action_End_case:
		return caseEnd(x.GetEnd())
	default:
		panic("MustMap_Action_Behavior: x.Behavior is not set")
	}
}

// Map_Action_Behavior maps x.Behavior to a value of type T by invoking
// one of the given functions.
//
// It invokes the function that corresponds to the value of x.Behavior,
// and returns that function's result. It calls none() if x.Behavior is nil.
func Map_Action_Behavior[T any](
	x *Action,
	caseFail func(string) T,
	caseLog func(string) T,
	caseExecuteCommand func(*anypb.Any) T,
	caseRecordEvent func(*anypb.Any) T,
	caseScheduleTimeout func(*ScheduleTimeoutDetails) T,
	caseDestroy func(*Empty) T,
	caseEnd func(*Empty) T,
	none func() T,
) T {
	switch x.WhichBehavior() {
	case Action_Fail_case:
		return caseFail(x.GetFail())
	case Action_Log_case:
		return caseLog(x.GetLog())
	case Action_ExecuteCommand_case:
		return caseExecuteCommand(x.GetExecuteCommand())
	case Action_RecordEvent_case:
		return caseRecordEvent(x.GetRecordEvent())
	case Action_ScheduleTimeout_case:
		return caseScheduleTimeout(x.GetScheduleTimeout())
	case Action_Destroy_case:
		return caseDestroy(x.GetDestroy())
	case Action_End_case:
		return caseEnd(x.GetEnd())
	default:
		return none()
	}
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*Action] to implement [encoding.BinaryMarshaler].
func (x *Action) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*Action] to implement [encoding.BinaryUnmarshaler].
func (x *Action) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*ScheduleTimeoutDetails] to implement [encoding.BinaryMarshaler].
func (x *ScheduleTimeoutDetails) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*ScheduleTimeoutDetails] to implement [encoding.BinaryUnmarshaler].
func (x *ScheduleTimeoutDetails) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*Empty] to implement [encoding.BinaryMarshaler].
func (x *Empty) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*Empty] to implement [encoding.BinaryUnmarshaler].
func (x *Empty) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}
