// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: github.com/dogmatiq/enginekit/enginetest/internal/action/action.proto

package action

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Behavior:
	//
	//	*Action_Fail
	//	*Action_Log
	//	*Action_ExecuteCommand
	//	*Action_RecordEvent
	//	*Action_ScheduleTimeout
	//	*Action_Destroy
	//	*Action_End
	Behavior      isAction_Behavior `protobuf_oneof:"behavior"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_rawDescGZIP(), []int{0}
}

func (x *Action) GetBehavior() isAction_Behavior {
	if x != nil {
		return x.Behavior
	}
	return nil
}

func (x *Action) GetFail() string {
	if x != nil {
		if x, ok := x.Behavior.(*Action_Fail); ok {
			return x.Fail
		}
	}
	return ""
}

func (x *Action) GetLog() string {
	if x != nil {
		if x, ok := x.Behavior.(*Action_Log); ok {
			return x.Log
		}
	}
	return ""
}

func (x *Action) GetExecuteCommand() *anypb.Any {
	if x != nil {
		if x, ok := x.Behavior.(*Action_ExecuteCommand); ok {
			return x.ExecuteCommand
		}
	}
	return nil
}

func (x *Action) GetRecordEvent() *anypb.Any {
	if x != nil {
		if x, ok := x.Behavior.(*Action_RecordEvent); ok {
			return x.RecordEvent
		}
	}
	return nil
}

func (x *Action) GetScheduleTimeout() *ScheduleTimeoutDetails {
	if x != nil {
		if x, ok := x.Behavior.(*Action_ScheduleTimeout); ok {
			return x.ScheduleTimeout
		}
	}
	return nil
}

func (x *Action) GetDestroy() *Empty {
	if x != nil {
		if x, ok := x.Behavior.(*Action_Destroy); ok {
			return x.Destroy
		}
	}
	return nil
}

func (x *Action) GetEnd() *Empty {
	if x != nil {
		if x, ok := x.Behavior.(*Action_End); ok {
			return x.End
		}
	}
	return nil
}

type isAction_Behavior interface {
	isAction_Behavior()
}

type Action_Fail struct {
	Fail string `protobuf:"bytes,1,opt,name=fail,proto3,oneof"`
}

type Action_Log struct {
	Log string `protobuf:"bytes,2,opt,name=log,proto3,oneof"`
}

type Action_ExecuteCommand struct {
	ExecuteCommand *anypb.Any `protobuf:"bytes,3,opt,name=execute_command,json=executeCommand,proto3,oneof"`
}

type Action_RecordEvent struct {
	RecordEvent *anypb.Any `protobuf:"bytes,4,opt,name=record_event,json=recordEvent,proto3,oneof"`
}

type Action_ScheduleTimeout struct {
	ScheduleTimeout *ScheduleTimeoutDetails `protobuf:"bytes,5,opt,name=schedule_timeout,json=scheduleTimeout,proto3,oneof"`
}

type Action_Destroy struct {
	Destroy *Empty `protobuf:"bytes,6,opt,name=destroy,proto3,oneof"`
}

type Action_End struct {
	End *Empty `protobuf:"bytes,7,opt,name=end,proto3,oneof"`
}

func (*Action_Fail) isAction_Behavior() {}

func (*Action_Log) isAction_Behavior() {}

func (*Action_ExecuteCommand) isAction_Behavior() {}

func (*Action_RecordEvent) isAction_Behavior() {}

func (*Action_ScheduleTimeout) isAction_Behavior() {}

func (*Action_Destroy) isAction_Behavior() {}

func (*Action_End) isAction_Behavior() {}

type ScheduleTimeoutDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timeout       *anypb.Any             `protobuf:"bytes,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleTimeoutDetails) Reset() {
	*x = ScheduleTimeoutDetails{}
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTimeoutDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTimeoutDetails) ProtoMessage() {}

func (x *ScheduleTimeoutDetails) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTimeoutDetails.ProtoReflect.Descriptor instead.
func (*ScheduleTimeoutDetails) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleTimeoutDetails) GetTimeout() *anypb.Any {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *ScheduleTimeoutDetails) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_rawDescGZIP(), []int{2}
}

var File_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_rawDesc = "" +
	"\n" +
	"Egithub.com/dogmatiq/enginekit/enginetest/internal/action/action.proto\x12\x1ddogmatiq.enginekit.enginetest\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x03\n" +
	"\x06Action\x12\x14\n" +
	"\x04fail\x18\x01 \x01(\tH\x00R\x04fail\x12\x12\n" +
	"\x03log\x18\x02 \x01(\tH\x00R\x03log\x12?\n" +
	"\x0fexecute_command\x18\x03 \x01(\v2\x14.google.protobuf.AnyH\x00R\x0eexecuteCommand\x129\n" +
	"\frecord_event\x18\x04 \x01(\v2\x14.google.protobuf.AnyH\x00R\vrecordEvent\x12b\n" +
	"\x10schedule_timeout\x18\x05 \x01(\v25.dogmatiq.enginekit.enginetest.ScheduleTimeoutDetailsH\x00R\x0fscheduleTimeout\x12@\n" +
	"\adestroy\x18\x06 \x01(\v2$.dogmatiq.enginekit.enginetest.EmptyH\x00R\adestroy\x128\n" +
	"\x03end\x18\a \x01(\v2$.dogmatiq.enginekit.enginetest.EmptyH\x00R\x03endB\n" +
	"\n" +
	"\bbehavior\"t\n" +
	"\x16ScheduleTimeoutDetails\x12.\n" +
	"\atimeout\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\atimeout\x12*\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"\a\n" +
	"\x05EmptyB:Z8github.com/dogmatiq/enginekit/enginetest/internal/actionb\x06proto3"

var (
	file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_rawDescData []byte
)

func file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_rawDesc), len(file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_rawDescData
}

var file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_goTypes = []any{
	(*Action)(nil),                 // 0: dogmatiq.enginekit.enginetest.Action
	(*ScheduleTimeoutDetails)(nil), // 1: dogmatiq.enginekit.enginetest.ScheduleTimeoutDetails
	(*Empty)(nil),                  // 2: dogmatiq.enginekit.enginetest.Empty
	(*anypb.Any)(nil),              // 3: google.protobuf.Any
	(*timestamppb.Timestamp)(nil),  // 4: google.protobuf.Timestamp
}
var file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_depIdxs = []int32{
	3, // 0: dogmatiq.enginekit.enginetest.Action.execute_command:type_name -> google.protobuf.Any
	3, // 1: dogmatiq.enginekit.enginetest.Action.record_event:type_name -> google.protobuf.Any
	1, // 2: dogmatiq.enginekit.enginetest.Action.schedule_timeout:type_name -> dogmatiq.enginekit.enginetest.ScheduleTimeoutDetails
	2, // 3: dogmatiq.enginekit.enginetest.Action.destroy:type_name -> dogmatiq.enginekit.enginetest.Empty
	2, // 4: dogmatiq.enginekit.enginetest.Action.end:type_name -> dogmatiq.enginekit.enginetest.Empty
	3, // 5: dogmatiq.enginekit.enginetest.ScheduleTimeoutDetails.timeout:type_name -> google.protobuf.Any
	4, // 6: dogmatiq.enginekit.enginetest.ScheduleTimeoutDetails.at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_init() }
func file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_init() {
	if File_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto != nil {
		return
	}
	file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_msgTypes[0].OneofWrappers = []any{
		(*Action_Fail)(nil),
		(*Action_Log)(nil),
		(*Action_ExecuteCommand)(nil),
		(*Action_RecordEvent)(nil),
		(*Action_ScheduleTimeout)(nil),
		(*Action_Destroy)(nil),
		(*Action_End)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_rawDesc), len(file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto = out.File
	file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_goTypes = nil
	file_github_com_dogmatiq_enginekit_enginetest_internal_action_action_proto_depIdxs = nil
}
