// Code generated by protoc-gen-go-primo. DO NOT EDIT.
// versions:
// 	protoc-gen-go-primo v
// 	protoc              v6.33.1
// source: github.com/dogmatiq/enginekit/grpc/eventstreamgrpc/consume.proto

package eventstreamgrpc

import (
	"context"
	envelopepb "github.com/dogmatiq/enginekit/protobuf/envelopepb"
	uuidpb "github.com/dogmatiq/enginekit/protobuf/uuidpb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	proto "google.golang.org/protobuf/proto"
)

// TryGetEventDelivery returns x.Operation.EventDelivery if x.Operation is a [ConsumeEventsResponse_EventDelivery_].
// Otherwise, ok is false and v is the zero-value.
func (x *ConsumeEventsResponse) TryGetEventDelivery() (v *ConsumeEventsResponse_EventDelivery, ok bool) {
	if x, ok := x.GetOperation().(*ConsumeEventsResponse_EventDelivery_); ok {
		return x.EventDelivery, true
	}
	return v, false
}

type ListStreamsRequestBuilder struct {
	prototype ListStreamsRequest
}

// NewListStreamsRequestBuilder returns a builder that constructs [ListStreamsRequest] messages.
func NewListStreamsRequestBuilder() *ListStreamsRequestBuilder {
	return &ListStreamsRequestBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *ListStreamsRequestBuilder) From(x *ListStreamsRequest) *ListStreamsRequestBuilder {
	return b
}

// Build returns a new [ListStreamsRequest] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *ListStreamsRequestBuilder) Build() *ListStreamsRequest {
	return &ListStreamsRequest{}
}

type ListStreamsResponseBuilder struct {
	prototype ListStreamsResponse
}

// NewListStreamsResponseBuilder returns a builder that constructs [ListStreamsResponse] messages.
func NewListStreamsResponseBuilder() *ListStreamsResponseBuilder {
	return &ListStreamsResponseBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *ListStreamsResponseBuilder) From(x *ListStreamsResponse) *ListStreamsResponseBuilder {
	b.prototype.Streams = x.Streams
	return b
}

// Build returns a new [ListStreamsResponse] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *ListStreamsResponseBuilder) Build() *ListStreamsResponse {
	return &ListStreamsResponse{
		Streams: b.prototype.Streams,
	}
}

// WithStreams configures the builder to set the Streams field to v,
// then returns b.
func (b *ListStreamsResponseBuilder) WithStreams(v []*Stream) *ListStreamsResponseBuilder {
	b.prototype.Streams = v
	return b
}

type StreamBuilder struct {
	prototype Stream
}

// NewStreamBuilder returns a builder that constructs [Stream] messages.
func NewStreamBuilder() *StreamBuilder {
	return &StreamBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *StreamBuilder) From(x *Stream) *StreamBuilder {
	b.prototype.StreamId = x.StreamId
	b.prototype.EventTypeIds = x.EventTypeIds
	return b
}

// Build returns a new [Stream] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *StreamBuilder) Build() *Stream {
	return &Stream{
		StreamId:     b.prototype.StreamId,
		EventTypeIds: b.prototype.EventTypeIds,
	}
}

// WithStreamId configures the builder to set the StreamId field to v,
// then returns b.
func (b *StreamBuilder) WithStreamId(v *uuidpb.UUID) *StreamBuilder {
	b.prototype.StreamId = v
	return b
}

// WithEventTypeIds configures the builder to set the EventTypeIds field to v,
// then returns b.
func (b *StreamBuilder) WithEventTypeIds(v []*uuidpb.UUID) *StreamBuilder {
	b.prototype.EventTypeIds = v
	return b
}

type ConsumeEventsRequestBuilder struct {
	prototype ConsumeEventsRequest
}

// NewConsumeEventsRequestBuilder returns a builder that constructs [ConsumeEventsRequest] messages.
func NewConsumeEventsRequestBuilder() *ConsumeEventsRequestBuilder {
	return &ConsumeEventsRequestBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *ConsumeEventsRequestBuilder) From(x *ConsumeEventsRequest) *ConsumeEventsRequestBuilder {
	b.prototype.StreamId = x.StreamId
	b.prototype.Offset = x.Offset
	b.prototype.EventTypeIds = x.EventTypeIds
	return b
}

// Build returns a new [ConsumeEventsRequest] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *ConsumeEventsRequestBuilder) Build() *ConsumeEventsRequest {
	return &ConsumeEventsRequest{
		StreamId:     b.prototype.StreamId,
		Offset:       b.prototype.Offset,
		EventTypeIds: b.prototype.EventTypeIds,
	}
}

// WithStreamId configures the builder to set the StreamId field to v,
// then returns b.
func (b *ConsumeEventsRequestBuilder) WithStreamId(v *uuidpb.UUID) *ConsumeEventsRequestBuilder {
	b.prototype.StreamId = v
	return b
}

// WithOffset configures the builder to set the Offset field to v,
// then returns b.
func (b *ConsumeEventsRequestBuilder) WithOffset(v uint64) *ConsumeEventsRequestBuilder {
	b.prototype.Offset = v
	return b
}

// WithEventTypeIds configures the builder to set the EventTypeIds field to v,
// then returns b.
func (b *ConsumeEventsRequestBuilder) WithEventTypeIds(v []*uuidpb.UUID) *ConsumeEventsRequestBuilder {
	b.prototype.EventTypeIds = v
	return b
}

type ConsumeEventsResponseBuilder struct {
	prototype ConsumeEventsResponse
}

// NewConsumeEventsResponseBuilder returns a builder that constructs [ConsumeEventsResponse] messages.
func NewConsumeEventsResponseBuilder() *ConsumeEventsResponseBuilder {
	return &ConsumeEventsResponseBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *ConsumeEventsResponseBuilder) From(x *ConsumeEventsResponse) *ConsumeEventsResponseBuilder {
	b.prototype.Operation = x.Operation
	return b
}

// Build returns a new [ConsumeEventsResponse] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *ConsumeEventsResponseBuilder) Build() *ConsumeEventsResponse {
	return &ConsumeEventsResponse{
		Operation: b.prototype.Operation,
	}
}

// WithEventDelivery configures the builder to set the Operation field to a
// [ConsumeEventsResponse_EventDelivery_] value containing v, then returns b
func (b *ConsumeEventsResponseBuilder) WithEventDelivery(v *ConsumeEventsResponse_EventDelivery) *ConsumeEventsResponseBuilder {
	b.prototype.Operation = &ConsumeEventsResponse_EventDelivery_{EventDelivery: v}
	return b
}

type ConsumeEventsResponse_EventDeliveryBuilder struct {
	prototype ConsumeEventsResponse_EventDelivery
}

// NewConsumeEventsResponse_EventDeliveryBuilder returns a builder that constructs [ConsumeEventsResponse_EventDelivery] messages.
func NewConsumeEventsResponse_EventDeliveryBuilder() *ConsumeEventsResponse_EventDeliveryBuilder {
	return &ConsumeEventsResponse_EventDeliveryBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *ConsumeEventsResponse_EventDeliveryBuilder) From(x *ConsumeEventsResponse_EventDelivery) *ConsumeEventsResponse_EventDeliveryBuilder {
	b.prototype.Offset = x.Offset
	b.prototype.Envelope = x.Envelope
	return b
}

// Build returns a new [ConsumeEventsResponse_EventDelivery] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *ConsumeEventsResponse_EventDeliveryBuilder) Build() *ConsumeEventsResponse_EventDelivery {
	return &ConsumeEventsResponse_EventDelivery{
		Offset:   b.prototype.Offset,
		Envelope: b.prototype.Envelope,
	}
}

// WithOffset configures the builder to set the Offset field to v,
// then returns b.
func (b *ConsumeEventsResponse_EventDeliveryBuilder) WithOffset(v uint64) *ConsumeEventsResponse_EventDeliveryBuilder {
	b.prototype.Offset = v
	return b
}

// WithEnvelope configures the builder to set the Envelope field to v,
// then returns b.
func (b *ConsumeEventsResponse_EventDeliveryBuilder) WithEnvelope(v *envelopepb.Envelope) *ConsumeEventsResponse_EventDeliveryBuilder {
	b.prototype.Envelope = v
	return b
}

type UnrecognizedStreamBuilder struct {
	prototype UnrecognizedStream
}

// NewUnrecognizedStreamBuilder returns a builder that constructs [UnrecognizedStream] messages.
func NewUnrecognizedStreamBuilder() *UnrecognizedStreamBuilder {
	return &UnrecognizedStreamBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *UnrecognizedStreamBuilder) From(x *UnrecognizedStream) *UnrecognizedStreamBuilder {
	b.prototype.StreamId = x.StreamId
	return b
}

// Build returns a new [UnrecognizedStream] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *UnrecognizedStreamBuilder) Build() *UnrecognizedStream {
	return &UnrecognizedStream{
		StreamId: b.prototype.StreamId,
	}
}

// WithStreamId configures the builder to set the StreamId field to v,
// then returns b.
func (b *UnrecognizedStreamBuilder) WithStreamId(v *uuidpb.UUID) *UnrecognizedStreamBuilder {
	b.prototype.StreamId = v
	return b
}

type NoEventTypesBuilder struct {
	prototype NoEventTypes
}

// NewNoEventTypesBuilder returns a builder that constructs [NoEventTypes] messages.
func NewNoEventTypesBuilder() *NoEventTypesBuilder {
	return &NoEventTypesBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *NoEventTypesBuilder) From(x *NoEventTypes) *NoEventTypesBuilder {
	return b
}

// Build returns a new [NoEventTypes] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *NoEventTypesBuilder) Build() *NoEventTypes {
	return &NoEventTypes{}
}

type UnrecognizedEventTypeBuilder struct {
	prototype UnrecognizedEventType
}

// NewUnrecognizedEventTypeBuilder returns a builder that constructs [UnrecognizedEventType] messages.
func NewUnrecognizedEventTypeBuilder() *UnrecognizedEventTypeBuilder {
	return &UnrecognizedEventTypeBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *UnrecognizedEventTypeBuilder) From(x *UnrecognizedEventType) *UnrecognizedEventTypeBuilder {
	b.prototype.EventTypeId = x.EventTypeId
	return b
}

// Build returns a new [UnrecognizedEventType] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *UnrecognizedEventTypeBuilder) Build() *UnrecognizedEventType {
	return &UnrecognizedEventType{
		EventTypeId: b.prototype.EventTypeId,
	}
}

// WithEventTypeId configures the builder to set the EventTypeId field to v,
// then returns b.
func (b *UnrecognizedEventTypeBuilder) WithEventTypeId(v *uuidpb.UUID) *UnrecognizedEventTypeBuilder {
	b.prototype.EventTypeId = v
	return b
}

// MustSwitch_ConsumeEventsResponse_Operation invokes one of the given functions based on
// the value of x.Operation.
//
// It panics if x.Operation is nil.
func MustSwitch_ConsumeEventsResponse_Operation(
	x *ConsumeEventsResponse,
	caseEventDelivery func(*ConsumeEventsResponse_EventDelivery),
) {
	switch v := x.GetOperation().(type) {
	case *ConsumeEventsResponse_EventDelivery_:
		caseEventDelivery(v.EventDelivery)
	default:
		panic("MustSwitch_ConsumeEventsResponse_Operation: x.Operation is nil")
	}
}

// Switch_ConsumeEventsResponse_Operation invokes one of the given functions based on
// the value of x.Operation.
//
// It calls none() if x.Operation is nil.
func Switch_ConsumeEventsResponse_Operation(
	x *ConsumeEventsResponse,
	caseEventDelivery func(*ConsumeEventsResponse_EventDelivery),
	none func(),
) {
	switch v := x.GetOperation().(type) {
	case *ConsumeEventsResponse_EventDelivery_:
		caseEventDelivery(v.EventDelivery)
	default:
		none()
	}
}

// MustMap_ConsumeEventsResponse_Operation maps x.Operation to a value of type T by invoking
// one of the given functions.
//
// It invokes the function that corresponds to the value of x.Operation,
// and returns that function's result. It panics if x.Operation is nil.
func MustMap_ConsumeEventsResponse_Operation[T any](
	x *ConsumeEventsResponse,
	caseEventDelivery func(*ConsumeEventsResponse_EventDelivery) T,
) T {
	switch v := x.GetOperation().(type) {
	case *ConsumeEventsResponse_EventDelivery_:
		return caseEventDelivery(v.EventDelivery)
	default:
		panic("MustMap_ConsumeEventsResponse_Operation: x.Operation is nil")
	}
}

// Map_ConsumeEventsResponse_Operation maps x.Operation to a value of type T by invoking
// one of the given functions.
//
// It invokes the function that corresponds to the value of x.Operation,
// and returns that function's result. It calls none() if x.Operation is nil.
func Map_ConsumeEventsResponse_Operation[T any](
	x *ConsumeEventsResponse,
	caseEventDelivery func(*ConsumeEventsResponse_EventDelivery) T,
	none func() T,
) T {
	switch v := x.GetOperation().(type) {
	case *ConsumeEventsResponse_EventDelivery_:
		return caseEventDelivery(v.EventDelivery)
	default:
		return none()
	}
}

// ConsumeAPIClientStub is a test implementation of the [ConsumeAPIClient] interface.
var _ ConsumeAPIClient = (*ConsumeAPIClientStub)(nil)

type ConsumeAPIClientStub struct {
	// ListStreamsFunc is a function that implements the ListStreams RPC method.
	ListStreamsFunc func(ctx context.Context, req *ListStreamsRequest, options ...grpc.CallOption) (*ListStreamsResponse, error)

	// ConsumeEventsFunc is a function that implements the ConsumeEvents RPC method.
	ConsumeEventsFunc func(ctx context.Context, req *ConsumeEventsRequest, options ...grpc.CallOption) (ConsumeAPI_ConsumeEventsClient, error)
}

// ListStreams calls c.ListStreamsFunc if it is non-nil. Otherwise, it returns an error.
func (c *ConsumeAPIClientStub) ListStreams(ctx context.Context, req *ListStreamsRequest, options ...grpc.CallOption) (*ListStreamsResponse, error) {
	if c.ListStreamsFunc == nil {
		return nil, status.Error(codes.Unimplemented, "method ListStreams not implemented")
	}
	return c.ListStreamsFunc(ctx, req, options...)
}

// ConsumeEvents calls c.ConsumeEventsFunc if it is non-nil. Otherwise, it returns an error.
func (c *ConsumeAPIClientStub) ConsumeEvents(ctx context.Context, req *ConsumeEventsRequest, options ...grpc.CallOption) (ConsumeAPI_ConsumeEventsClient, error) {
	if c.ConsumeEventsFunc == nil {
		return nil, status.Error(codes.Unimplemented, "method ConsumeEvents not implemented")
	}
	return c.ConsumeEventsFunc(ctx, req, options...)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*ListStreamsRequest] to implement [encoding.BinaryMarshaler].
func (x *ListStreamsRequest) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*ListStreamsRequest] to implement [encoding.BinaryUnmarshaler].
func (x *ListStreamsRequest) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*ListStreamsResponse] to implement [encoding.BinaryMarshaler].
func (x *ListStreamsResponse) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*ListStreamsResponse] to implement [encoding.BinaryUnmarshaler].
func (x *ListStreamsResponse) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*Stream] to implement [encoding.BinaryMarshaler].
func (x *Stream) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*Stream] to implement [encoding.BinaryUnmarshaler].
func (x *Stream) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*ConsumeEventsRequest] to implement [encoding.BinaryMarshaler].
func (x *ConsumeEventsRequest) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*ConsumeEventsRequest] to implement [encoding.BinaryUnmarshaler].
func (x *ConsumeEventsRequest) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*ConsumeEventsResponse] to implement [encoding.BinaryMarshaler].
func (x *ConsumeEventsResponse) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*ConsumeEventsResponse] to implement [encoding.BinaryUnmarshaler].
func (x *ConsumeEventsResponse) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*ConsumeEventsResponse_EventDelivery] to implement [encoding.BinaryMarshaler].
func (x *ConsumeEventsResponse_EventDelivery) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*ConsumeEventsResponse_EventDelivery] to implement [encoding.BinaryUnmarshaler].
func (x *ConsumeEventsResponse_EventDelivery) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*UnrecognizedStream] to implement [encoding.BinaryMarshaler].
func (x *UnrecognizedStream) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*UnrecognizedStream] to implement [encoding.BinaryUnmarshaler].
func (x *UnrecognizedStream) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*NoEventTypes] to implement [encoding.BinaryMarshaler].
func (x *NoEventTypes) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*NoEventTypes] to implement [encoding.BinaryUnmarshaler].
func (x *NoEventTypes) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*UnrecognizedEventType] to implement [encoding.BinaryMarshaler].
func (x *UnrecognizedEventType) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*UnrecognizedEventType] to implement [encoding.BinaryUnmarshaler].
func (x *UnrecognizedEventType) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// SetStreams sets the x.Streams field to v, then returns x.
func (x *ListStreamsResponse) SetStreams(v []*Stream) {
	x.Streams = v
}

// SetStreamId sets the x.StreamId field to v, then returns x.
func (x *Stream) SetStreamId(v *uuidpb.UUID) {
	x.StreamId = v
}

// SetEventTypeIds sets the x.EventTypeIds field to v, then returns x.
func (x *Stream) SetEventTypeIds(v []*uuidpb.UUID) {
	x.EventTypeIds = v
}

// SetStreamId sets the x.StreamId field to v, then returns x.
func (x *ConsumeEventsRequest) SetStreamId(v *uuidpb.UUID) {
	x.StreamId = v
}

// SetOffset sets the x.Offset field to v, then returns x.
func (x *ConsumeEventsRequest) SetOffset(v uint64) {
	x.Offset = v
}

// SetEventTypeIds sets the x.EventTypeIds field to v, then returns x.
func (x *ConsumeEventsRequest) SetEventTypeIds(v []*uuidpb.UUID) {
	x.EventTypeIds = v
}

// SetEventDelivery sets the x.Operation field to a [ConsumeEventsResponse_EventDelivery_] value containing v,
// then returns x.
func (x *ConsumeEventsResponse) SetEventDelivery(v *ConsumeEventsResponse_EventDelivery) {
	x.Operation = &ConsumeEventsResponse_EventDelivery_{EventDelivery: v}
}

// SetOffset sets the x.Offset field to v, then returns x.
func (x *ConsumeEventsResponse_EventDelivery) SetOffset(v uint64) {
	x.Offset = v
}

// SetEnvelope sets the x.Envelope field to v, then returns x.
func (x *ConsumeEventsResponse_EventDelivery) SetEnvelope(v *envelopepb.Envelope) {
	x.Envelope = v
}

// SetStreamId sets the x.StreamId field to v, then returns x.
func (x *UnrecognizedStream) SetStreamId(v *uuidpb.UUID) {
	x.StreamId = v
}

// SetEventTypeId sets the x.EventTypeId field to v, then returns x.
func (x *UnrecognizedEventType) SetEventTypeId(v *uuidpb.UUID) {
	x.EventTypeId = v
}
