// Code generated by protoc-gen-go-primo. DO NOT EDIT.
// versions:
// 	protoc-gen-go-primo v
// 	protoc              v6.33.1
// source: github.com/dogmatiq/enginekit/grpc/messaginggrpc/eventstreamconsumer.proto

package messaginggrpc

import (
	"context"
	envelopepb "github.com/dogmatiq/enginekit/protobuf/envelopepb"
	uuidpb "github.com/dogmatiq/enginekit/protobuf/uuidpb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	proto "google.golang.org/protobuf/proto"
)

type ListEventStreamsRequestBuilder struct {
	prototype ListEventStreamsRequest
}

// NewListEventStreamsRequestBuilder returns a builder that constructs [ListEventStreamsRequest] messages.
func NewListEventStreamsRequestBuilder() *ListEventStreamsRequestBuilder {
	return &ListEventStreamsRequestBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *ListEventStreamsRequestBuilder) From(x *ListEventStreamsRequest) *ListEventStreamsRequestBuilder {
	proto.Reset(&b.prototype)
	return b
}

// Build returns a new [ListEventStreamsRequest] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *ListEventStreamsRequestBuilder) Build() *ListEventStreamsRequest {
	m := &ListEventStreamsRequest{}
	return m
}

type ListEventStreamsResponseBuilder struct {
	prototype ListEventStreamsResponse
}

// NewListEventStreamsResponseBuilder returns a builder that constructs [ListEventStreamsResponse] messages.
func NewListEventStreamsResponseBuilder() *ListEventStreamsResponseBuilder {
	return &ListEventStreamsResponseBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *ListEventStreamsResponseBuilder) From(x *ListEventStreamsResponse) *ListEventStreamsResponseBuilder {
	proto.Reset(&b.prototype)
	if x.HasEventStream() {
		b.prototype.SetEventStream(x.GetEventStream())
	}
	return b
}

// Build returns a new [ListEventStreamsResponse] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *ListEventStreamsResponseBuilder) Build() *ListEventStreamsResponse {
	m := &ListEventStreamsResponse{}
	if b.prototype.HasEventStream() {
		m.SetEventStream(b.prototype.GetEventStream())
	}
	return m
}

// WithEventStream configures the builder to set the EventStream field to v,
// then returns b.
func (b *ListEventStreamsResponseBuilder) WithEventStream(v *EventStream) *ListEventStreamsResponseBuilder {
	b.prototype.SetEventStream(v)
	return b
}

type EventStreamBuilder struct {
	prototype EventStream
}

// NewEventStreamBuilder returns a builder that constructs [EventStream] messages.
func NewEventStreamBuilder() *EventStreamBuilder {
	return &EventStreamBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *EventStreamBuilder) From(x *EventStream) *EventStreamBuilder {
	proto.Reset(&b.prototype)
	if x.HasEventStreamId() {
		b.prototype.SetEventStreamId(x.GetEventStreamId())
	}
	b.prototype.SetNextOffset(x.GetNextOffset())
	return b
}

// Build returns a new [EventStream] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *EventStreamBuilder) Build() *EventStream {
	m := &EventStream{}
	if b.prototype.HasEventStreamId() {
		m.SetEventStreamId(b.prototype.GetEventStreamId())
	}
	m.SetNextOffset(b.prototype.GetNextOffset())
	return m
}

// WithEventStreamId configures the builder to set the EventStreamId field to v,
// then returns b.
func (b *EventStreamBuilder) WithEventStreamId(v *uuidpb.UUID) *EventStreamBuilder {
	b.prototype.SetEventStreamId(v)
	return b
}

// WithNextOffset configures the builder to set the NextOffset field to v,
// then returns b.
func (b *EventStreamBuilder) WithNextOffset(v uint64) *EventStreamBuilder {
	b.prototype.SetNextOffset(v)
	return b
}

type ConsumeEventsRequestBuilder struct {
	prototype ConsumeEventsRequest
}

// NewConsumeEventsRequestBuilder returns a builder that constructs [ConsumeEventsRequest] messages.
func NewConsumeEventsRequestBuilder() *ConsumeEventsRequestBuilder {
	return &ConsumeEventsRequestBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *ConsumeEventsRequestBuilder) From(x *ConsumeEventsRequest) *ConsumeEventsRequestBuilder {
	proto.Reset(&b.prototype)
	if x.HasEventStreamId() {
		b.prototype.SetEventStreamId(x.GetEventStreamId())
	}
	b.prototype.SetCheckpointOffset(x.GetCheckpointOffset())
	b.prototype.SetMessageTypeIds(x.GetMessageTypeIds())
	return b
}

// Build returns a new [ConsumeEventsRequest] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *ConsumeEventsRequestBuilder) Build() *ConsumeEventsRequest {
	m := &ConsumeEventsRequest{}
	if b.prototype.HasEventStreamId() {
		m.SetEventStreamId(b.prototype.GetEventStreamId())
	}
	m.SetCheckpointOffset(b.prototype.GetCheckpointOffset())
	m.SetMessageTypeIds(b.prototype.GetMessageTypeIds())
	return m
}

// WithEventStreamId configures the builder to set the EventStreamId field to v,
// then returns b.
func (b *ConsumeEventsRequestBuilder) WithEventStreamId(v *uuidpb.UUID) *ConsumeEventsRequestBuilder {
	b.prototype.SetEventStreamId(v)
	return b
}

// WithCheckpointOffset configures the builder to set the CheckpointOffset field to v,
// then returns b.
func (b *ConsumeEventsRequestBuilder) WithCheckpointOffset(v uint64) *ConsumeEventsRequestBuilder {
	b.prototype.SetCheckpointOffset(v)
	return b
}

// WithMessageTypeIds configures the builder to set the MessageTypeIds field to v,
// then returns b.
func (b *ConsumeEventsRequestBuilder) WithMessageTypeIds(v []*uuidpb.UUID) *ConsumeEventsRequestBuilder {
	b.prototype.SetMessageTypeIds(v)
	return b
}

type ConsumeEventsResponseBuilder struct {
	prototype ConsumeEventsResponse
}

// NewConsumeEventsResponseBuilder returns a builder that constructs [ConsumeEventsResponse] messages.
func NewConsumeEventsResponseBuilder() *ConsumeEventsResponseBuilder {
	return &ConsumeEventsResponseBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *ConsumeEventsResponseBuilder) From(x *ConsumeEventsResponse) *ConsumeEventsResponseBuilder {
	proto.Reset(&b.prototype)
	b.prototype.SetCheckpointOffset(x.GetCheckpointOffset())
	b.prototype.SetEnvelopes(x.GetEnvelopes())
	return b
}

// Build returns a new [ConsumeEventsResponse] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *ConsumeEventsResponseBuilder) Build() *ConsumeEventsResponse {
	m := &ConsumeEventsResponse{}
	m.SetCheckpointOffset(b.prototype.GetCheckpointOffset())
	m.SetEnvelopes(b.prototype.GetEnvelopes())
	return m
}

// WithCheckpointOffset configures the builder to set the CheckpointOffset field to v,
// then returns b.
func (b *ConsumeEventsResponseBuilder) WithCheckpointOffset(v uint64) *ConsumeEventsResponseBuilder {
	b.prototype.SetCheckpointOffset(v)
	return b
}

// WithEnvelopes configures the builder to set the Envelopes field to v,
// then returns b.
func (b *ConsumeEventsResponseBuilder) WithEnvelopes(v []*envelopepb.MultiEnvelope) *ConsumeEventsResponseBuilder {
	b.prototype.SetEnvelopes(v)
	return b
}

// EventStreamConsumerAPIClientStub is a test implementation of the [EventStreamConsumerAPIClient] interface.
var _ EventStreamConsumerAPIClient = (*EventStreamConsumerAPIClientStub)(nil)

type EventStreamConsumerAPIClientStub struct {
	// ListEventStreamsFunc is a function that implements the ListEventStreams RPC method.
	ListEventStreamsFunc func(ctx context.Context, req *ListEventStreamsRequest, options ...grpc.CallOption) (EventStreamConsumerAPI_ListEventStreamsClient, error)

	// ConsumeEventsFunc is a function that implements the ConsumeEvents RPC method.
	ConsumeEventsFunc func(ctx context.Context, req *ConsumeEventsRequest, options ...grpc.CallOption) (EventStreamConsumerAPI_ConsumeEventsClient, error)
}

// ListEventStreams calls c.ListEventStreamsFunc if it is non-nil. Otherwise, it returns an error.
func (c *EventStreamConsumerAPIClientStub) ListEventStreams(ctx context.Context, req *ListEventStreamsRequest, options ...grpc.CallOption) (EventStreamConsumerAPI_ListEventStreamsClient, error) {
	if c.ListEventStreamsFunc == nil {
		return nil, status.Error(codes.Unimplemented, "method ListEventStreams not implemented")
	}
	return c.ListEventStreamsFunc(ctx, req, options...)
}

// ConsumeEvents calls c.ConsumeEventsFunc if it is non-nil. Otherwise, it returns an error.
func (c *EventStreamConsumerAPIClientStub) ConsumeEvents(ctx context.Context, req *ConsumeEventsRequest, options ...grpc.CallOption) (EventStreamConsumerAPI_ConsumeEventsClient, error) {
	if c.ConsumeEventsFunc == nil {
		return nil, status.Error(codes.Unimplemented, "method ConsumeEvents not implemented")
	}
	return c.ConsumeEventsFunc(ctx, req, options...)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*ListEventStreamsRequest] to implement [encoding.BinaryMarshaler].
func (x *ListEventStreamsRequest) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*ListEventStreamsRequest] to implement [encoding.BinaryUnmarshaler].
func (x *ListEventStreamsRequest) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*ListEventStreamsResponse] to implement [encoding.BinaryMarshaler].
func (x *ListEventStreamsResponse) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*ListEventStreamsResponse] to implement [encoding.BinaryUnmarshaler].
func (x *ListEventStreamsResponse) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*EventStream] to implement [encoding.BinaryMarshaler].
func (x *EventStream) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*EventStream] to implement [encoding.BinaryUnmarshaler].
func (x *EventStream) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*ConsumeEventsRequest] to implement [encoding.BinaryMarshaler].
func (x *ConsumeEventsRequest) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*ConsumeEventsRequest] to implement [encoding.BinaryUnmarshaler].
func (x *ConsumeEventsRequest) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*ConsumeEventsResponse] to implement [encoding.BinaryMarshaler].
func (x *ConsumeEventsResponse) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*ConsumeEventsResponse] to implement [encoding.BinaryUnmarshaler].
func (x *ConsumeEventsResponse) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}
