// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.1
// source: github.com/dogmatiq/enginekit/grpc/messaginggrpc/eventstreamconsumer.proto

package messaginggrpc

import (
	envelopepb "github.com/dogmatiq/enginekit/protobuf/envelopepb"
	uuidpb "github.com/dogmatiq/enginekit/protobuf/uuidpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListEventStreamsRequest is the input to the
// [EventStreamConsumerAPI.ListEventStreams] method.
type ListEventStreamsRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventStreamsRequest) Reset() {
	*x = ListEventStreamsRequest{}
	mi := &file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventStreamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventStreamsRequest) ProtoMessage() {}

func (x *ListEventStreamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ListEventStreamsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ListEventStreamsRequest_builder) Build() *ListEventStreamsRequest {
	m0 := &ListEventStreamsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// ListEventStreamsResponse is the output of the
// [EventStreamConsumerAPI.ListEventStreams] method.
type ListEventStreamsResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EventStream *EventStream           `protobuf:"bytes,1,opt,name=event_stream,json=eventStream"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListEventStreamsResponse) Reset() {
	*x = ListEventStreamsResponse{}
	mi := &file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventStreamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventStreamsResponse) ProtoMessage() {}

func (x *ListEventStreamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListEventStreamsResponse) GetEventStream() *EventStream {
	if x != nil {
		return x.xxx_hidden_EventStream
	}
	return nil
}

func (x *ListEventStreamsResponse) SetEventStream(v *EventStream) {
	x.xxx_hidden_EventStream = v
}

func (x *ListEventStreamsResponse) HasEventStream() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EventStream != nil
}

func (x *ListEventStreamsResponse) ClearEventStream() {
	x.xxx_hidden_EventStream = nil
}

type ListEventStreamsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// EventStream is an event stream offered by the server.
	EventStream *EventStream
}

func (b0 ListEventStreamsResponse_builder) Build() *ListEventStreamsResponse {
	m0 := &ListEventStreamsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_EventStream = b.EventStream
	return m0
}

// EventStream describes an offset-based ordered event stream.
type EventStream struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EventStreamId *uuidpb.UUID           `protobuf:"bytes,1,opt,name=event_stream_id,json=eventStreamId"`
	xxx_hidden_NextOffset    uint64                 `protobuf:"varint,2,opt,name=next_offset,json=nextOffset"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *EventStream) Reset() {
	*x = EventStream{}
	mi := &file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStream) ProtoMessage() {}

func (x *EventStream) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventStream) GetEventStreamId() *uuidpb.UUID {
	if x != nil {
		return x.xxx_hidden_EventStreamId
	}
	return nil
}

func (x *EventStream) GetNextOffset() uint64 {
	if x != nil {
		return x.xxx_hidden_NextOffset
	}
	return 0
}

func (x *EventStream) SetEventStreamId(v *uuidpb.UUID) {
	x.xxx_hidden_EventStreamId = v
}

func (x *EventStream) SetNextOffset(v uint64) {
	x.xxx_hidden_NextOffset = v
}

func (x *EventStream) HasEventStreamId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EventStreamId != nil
}

func (x *EventStream) ClearEventStreamId() {
	x.xxx_hidden_EventStreamId = nil
}

type EventStream_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// EventStreamId is a unique identifier for the stream.
	EventStreamId *uuidpb.UUID
	// NextOffset is the offset of the next event that will be written to the
	// stream. The first event in the stream is at offset zero; therefore,
	// this value is equivalent to the number of events that have been written
	// to the stream.
	NextOffset uint64
}

func (b0 EventStream_builder) Build() *EventStream {
	m0 := &EventStream{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_EventStreamId = b.EventStreamId
	x.xxx_hidden_NextOffset = b.NextOffset
	return m0
}

// ConsumeEventsRequest is the input to the
// [EventStreamConsumerAPI.ConsumeEvents] method.
type ConsumeEventsRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EventStreamId    *uuidpb.UUID           `protobuf:"bytes,1,opt,name=event_stream_id,json=eventStreamId"`
	xxx_hidden_CheckpointOffset uint64                 `protobuf:"varint,2,opt,name=checkpoint_offset,json=checkpointOffset"`
	xxx_hidden_MessageTypeIds   *[]*uuidpb.UUID        `protobuf:"bytes,3,rep,name=message_type_ids,json=messageTypeIds"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ConsumeEventsRequest) Reset() {
	*x = ConsumeEventsRequest{}
	mi := &file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeEventsRequest) ProtoMessage() {}

func (x *ConsumeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConsumeEventsRequest) GetEventStreamId() *uuidpb.UUID {
	if x != nil {
		return x.xxx_hidden_EventStreamId
	}
	return nil
}

func (x *ConsumeEventsRequest) GetCheckpointOffset() uint64 {
	if x != nil {
		return x.xxx_hidden_CheckpointOffset
	}
	return 0
}

func (x *ConsumeEventsRequest) GetMessageTypeIds() []*uuidpb.UUID {
	if x != nil {
		if x.xxx_hidden_MessageTypeIds != nil {
			return *x.xxx_hidden_MessageTypeIds
		}
	}
	return nil
}

func (x *ConsumeEventsRequest) SetEventStreamId(v *uuidpb.UUID) {
	x.xxx_hidden_EventStreamId = v
}

func (x *ConsumeEventsRequest) SetCheckpointOffset(v uint64) {
	x.xxx_hidden_CheckpointOffset = v
}

func (x *ConsumeEventsRequest) SetMessageTypeIds(v []*uuidpb.UUID) {
	x.xxx_hidden_MessageTypeIds = &v
}

func (x *ConsumeEventsRequest) HasEventStreamId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EventStreamId != nil
}

func (x *ConsumeEventsRequest) ClearEventStreamId() {
	x.xxx_hidden_EventStreamId = nil
}

type ConsumeEventsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// EventStreamId is the ID from which events are consumed.
	EventStreamId *uuidpb.UUID
	// CheckpointOffset is the offset at which the consumer begins.
	CheckpointOffset uint64
	// MessageTypeIds is the set of message type IDs of the event types to
	// include in the responses.
	MessageTypeIds []*uuidpb.UUID
}

func (b0 ConsumeEventsRequest_builder) Build() *ConsumeEventsRequest {
	m0 := &ConsumeEventsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_EventStreamId = b.EventStreamId
	x.xxx_hidden_CheckpointOffset = b.CheckpointOffset
	x.xxx_hidden_MessageTypeIds = &b.MessageTypeIds
	return m0
}

// ConsumeEventsResponse is the (streaming) output of the
// [EventStreamConsumerAPI.ConsumeEvents] method.
//
// It contains all of the events that match the requested message type IDs
// specified in the [ConsumeEventsRequest], starting at the checkpoint offset up
// to, but not including, the checkpoint offset in this response.
//
// The list of events may be empty, indicating that there are no matching events
// in that range.
type ConsumeEventsResponse struct {
	state                       protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_CheckpointOffset uint64                       `protobuf:"varint,1,opt,name=checkpoint_offset,json=checkpointOffset"`
	xxx_hidden_Envelopes        *[]*envelopepb.MultiEnvelope `protobuf:"bytes,2,rep,name=envelopes"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ConsumeEventsResponse) Reset() {
	*x = ConsumeEventsResponse{}
	mi := &file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeEventsResponse) ProtoMessage() {}

func (x *ConsumeEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConsumeEventsResponse) GetCheckpointOffset() uint64 {
	if x != nil {
		return x.xxx_hidden_CheckpointOffset
	}
	return 0
}

func (x *ConsumeEventsResponse) GetEnvelopes() []*envelopepb.MultiEnvelope {
	if x != nil {
		if x.xxx_hidden_Envelopes != nil {
			return *x.xxx_hidden_Envelopes
		}
	}
	return nil
}

func (x *ConsumeEventsResponse) SetCheckpointOffset(v uint64) {
	x.xxx_hidden_CheckpointOffset = v
}

func (x *ConsumeEventsResponse) SetEnvelopes(v []*envelopepb.MultiEnvelope) {
	x.xxx_hidden_Envelopes = &v
}

type ConsumeEventsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// CheckpointOffset is the offset immediately after the range of the
	// stream described by this response.
	//
	// After handling this and all preceding responses, the client may use
	// this value as the checkpoint offset to resume consuming from the
	// stream in a subsequent [ConsumeEventsRequest].
	CheckpointOffset uint64
	// Envelopes is a (possibly empty) list of multi-envelopes containing
	// events at offsets between the prior checkpoint offset and the
	// checkpoint offset in this response.
	//
	// Each envelope includes the [envelopepb.EventStreamPosition] extension.
	//
	// The envelopes are ordered by the offset of the events they contain.
	// There is no additional relationship implied between envelopes that
	// appear in the same response.
	//
	// The offsets of the events within this response, or even within a
	// single [envelopepb.MultiEnvelope] are not necessarily contiguous.
	Envelopes []*envelopepb.MultiEnvelope
}

func (b0 ConsumeEventsResponse_builder) Build() *ConsumeEventsResponse {
	m0 := &ConsumeEventsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_CheckpointOffset = b.CheckpointOffset
	x.xxx_hidden_Envelopes = &b.Envelopes
	return m0
}

var File_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_rawDesc = "" +
	"\n" +
	"Jgithub.com/dogmatiq/enginekit/grpc/messaginggrpc/eventstreamconsumer.proto\x12\x12dogma.messaging.v1\x1a@github.com/dogmatiq/enginekit/protobuf/envelopepb/envelope.proto\x1a8github.com/dogmatiq/enginekit/protobuf/uuidpb/uuid.proto\"\x19\n" +
	"\x17ListEventStreamsRequest\"^\n" +
	"\x18ListEventStreamsResponse\x12B\n" +
	"\fevent_stream\x18\x01 \x01(\v2\x1f.dogma.messaging.v1.EventStreamR\veventStream\"s\n" +
	"\vEventStream\x12<\n" +
	"\x0fevent_stream_id\x18\x01 \x01(\v2\x14.dogma.protobuf.UUIDR\reventStreamId\x12&\n" +
	"\vnext_offset\x18\x02 \x01(\x04B\x05\xaa\x01\x02\b\x02R\n" +
	"nextOffset\"\xc8\x01\n" +
	"\x14ConsumeEventsRequest\x12<\n" +
	"\x0fevent_stream_id\x18\x01 \x01(\v2\x14.dogma.protobuf.UUIDR\reventStreamId\x122\n" +
	"\x11checkpoint_offset\x18\x02 \x01(\x04B\x05\xaa\x01\x02\b\x02R\x10checkpointOffset\x12>\n" +
	"\x10message_type_ids\x18\x03 \x03(\v2\x14.dogma.protobuf.UUIDR\x0emessageTypeIds\"\x88\x01\n" +
	"\x15ConsumeEventsResponse\x122\n" +
	"\x11checkpoint_offset\x18\x01 \x01(\x04B\x05\xaa\x01\x02\b\x02R\x10checkpointOffset\x12;\n" +
	"\tenvelopes\x18\x02 \x03(\v2\x1d.dogma.protobuf.MultiEnvelopeR\tenvelopes2\xf1\x01\n" +
	"\x16EventStreamConsumerAPI\x12o\n" +
	"\x10ListEventStreams\x12+.dogma.messaging.v1.ListEventStreamsRequest\x1a,.dogma.messaging.v1.ListEventStreamsResponse0\x01\x12f\n" +
	"\rConsumeEvents\x12(.dogma.messaging.v1.ConsumeEventsRequest\x1a).dogma.messaging.v1.ConsumeEventsResponse0\x01B2Z0github.com/dogmatiq/enginekit/grpc/messaginggrpcb\beditionsp\xe9\a"

var file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_goTypes = []any{
	(*ListEventStreamsRequest)(nil),  // 0: dogma.messaging.v1.ListEventStreamsRequest
	(*ListEventStreamsResponse)(nil), // 1: dogma.messaging.v1.ListEventStreamsResponse
	(*EventStream)(nil),              // 2: dogma.messaging.v1.EventStream
	(*ConsumeEventsRequest)(nil),     // 3: dogma.messaging.v1.ConsumeEventsRequest
	(*ConsumeEventsResponse)(nil),    // 4: dogma.messaging.v1.ConsumeEventsResponse
	(*uuidpb.UUID)(nil),              // 5: dogma.protobuf.UUID
	(*envelopepb.MultiEnvelope)(nil), // 6: dogma.protobuf.MultiEnvelope
}
var file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_depIdxs = []int32{
	2, // 0: dogma.messaging.v1.ListEventStreamsResponse.event_stream:type_name -> dogma.messaging.v1.EventStream
	5, // 1: dogma.messaging.v1.EventStream.event_stream_id:type_name -> dogma.protobuf.UUID
	5, // 2: dogma.messaging.v1.ConsumeEventsRequest.event_stream_id:type_name -> dogma.protobuf.UUID
	5, // 3: dogma.messaging.v1.ConsumeEventsRequest.message_type_ids:type_name -> dogma.protobuf.UUID
	6, // 4: dogma.messaging.v1.ConsumeEventsResponse.envelopes:type_name -> dogma.protobuf.MultiEnvelope
	0, // 5: dogma.messaging.v1.EventStreamConsumerAPI.ListEventStreams:input_type -> dogma.messaging.v1.ListEventStreamsRequest
	3, // 6: dogma.messaging.v1.EventStreamConsumerAPI.ConsumeEvents:input_type -> dogma.messaging.v1.ConsumeEventsRequest
	1, // 7: dogma.messaging.v1.EventStreamConsumerAPI.ListEventStreams:output_type -> dogma.messaging.v1.ListEventStreamsResponse
	4, // 8: dogma.messaging.v1.EventStreamConsumerAPI.ConsumeEvents:output_type -> dogma.messaging.v1.ConsumeEventsResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_init() }
func file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_init() {
	if File_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_rawDesc), len(file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto = out.File
	file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_goTypes = nil
	file_github_com_dogmatiq_enginekit_grpc_messaginggrpc_eventstreamconsumer_proto_depIdxs = nil
}
