// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config/api/internal/pb/config.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApplicationConfig struct {
	Identity             *Identity        `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Handlers             []*HandlerConfig `protobuf:"bytes,2,rep,name=handlers,proto3" json:"handlers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ApplicationConfig) Reset()         { *m = ApplicationConfig{} }
func (m *ApplicationConfig) String() string { return proto.CompactTextString(m) }
func (*ApplicationConfig) ProtoMessage()    {}
func (*ApplicationConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cf4959049744493, []int{0}
}

func (m *ApplicationConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationConfig.Unmarshal(m, b)
}
func (m *ApplicationConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationConfig.Marshal(b, m, deterministic)
}
func (m *ApplicationConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationConfig.Merge(m, src)
}
func (m *ApplicationConfig) XXX_Size() int {
	return xxx_messageInfo_ApplicationConfig.Size(m)
}
func (m *ApplicationConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationConfig proto.InternalMessageInfo

func (m *ApplicationConfig) GetIdentity() *Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *ApplicationConfig) GetHandlers() []*HandlerConfig {
	if m != nil {
		return m.Handlers
	}
	return nil
}

type HandlerConfig struct {
	Identity             *Identity         `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Type                 string            `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Consumed             map[string]string `protobuf:"bytes,3,rep,name=consumed,proto3" json:"consumed,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Produced             map[string]string `protobuf:"bytes,4,rep,name=produced,proto3" json:"produced,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HandlerConfig) Reset()         { *m = HandlerConfig{} }
func (m *HandlerConfig) String() string { return proto.CompactTextString(m) }
func (*HandlerConfig) ProtoMessage()    {}
func (*HandlerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cf4959049744493, []int{1}
}

func (m *HandlerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandlerConfig.Unmarshal(m, b)
}
func (m *HandlerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandlerConfig.Marshal(b, m, deterministic)
}
func (m *HandlerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandlerConfig.Merge(m, src)
}
func (m *HandlerConfig) XXX_Size() int {
	return xxx_messageInfo_HandlerConfig.Size(m)
}
func (m *HandlerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_HandlerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_HandlerConfig proto.InternalMessageInfo

func (m *HandlerConfig) GetIdentity() *Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *HandlerConfig) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *HandlerConfig) GetConsumed() map[string]string {
	if m != nil {
		return m.Consumed
	}
	return nil
}

func (m *HandlerConfig) GetProduced() map[string]string {
	if m != nil {
		return m.Produced
	}
	return nil
}

func init() {
	proto.RegisterType((*ApplicationConfig)(nil), "dogma.config.api.v1.ApplicationConfig")
	proto.RegisterType((*HandlerConfig)(nil), "dogma.config.api.v1.HandlerConfig")
	proto.RegisterMapType((map[string]string)(nil), "dogma.config.api.v1.HandlerConfig.ConsumedEntry")
	proto.RegisterMapType((map[string]string)(nil), "dogma.config.api.v1.HandlerConfig.ProducedEntry")
}

func init() {
	proto.RegisterFile("config/api/internal/pb/config.proto", fileDescriptor_2cf4959049744493)
}

var fileDescriptor_2cf4959049744493 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x5f, 0x4b, 0xf3, 0x30,
	0x14, 0xc6, 0x69, 0xb7, 0xf7, 0x65, 0xcb, 0x18, 0x68, 0xf4, 0xa2, 0x0c, 0x84, 0x31, 0x11, 0x76,
	0x95, 0xe8, 0x14, 0xf1, 0x0f, 0x08, 0x3a, 0x04, 0x05, 0x2f, 0xa4, 0x97, 0xde, 0xa5, 0x4d, 0xec,
	0x0e, 0x6b, 0x93, 0xd8, 0xa5, 0x83, 0x7e, 0x09, 0x3f, 0xad, 0x1f, 0x40, 0xda, 0xb4, 0x85, 0x42,
	0x45, 0xc5, 0xbb, 0x93, 0x93, 0xe7, 0xf7, 0x9c, 0xf3, 0xc0, 0x41, 0x87, 0xa1, 0x92, 0xaf, 0x10,
	0x51, 0xa6, 0x81, 0x82, 0x34, 0x22, 0x95, 0x2c, 0xa6, 0x3a, 0xa0, 0xb6, 0x4d, 0x74, 0xaa, 0x8c,
	0xc2, 0x7b, 0x5c, 0x45, 0x09, 0x23, 0x55, 0x8f, 0x69, 0x20, 0xdb, 0x93, 0xc9, 0xd1, 0x17, 0x24,
	0x70, 0x21, 0x0d, 0x98, 0xdc, 0xb2, 0xb3, 0x77, 0x07, 0xed, 0xde, 0x6a, 0x1d, 0x43, 0xc8, 0x0c,
	0x28, 0xb9, 0x2c, 0x21, 0x7c, 0x89, 0x06, 0xb5, 0xce, 0x73, 0xa6, 0xce, 0x7c, 0xb4, 0x38, 0x20,
	0x1d, 0x43, 0xc8, 0x63, 0x25, 0xf2, 0x1b, 0x39, 0xbe, 0x41, 0x83, 0x15, 0x93, 0x3c, 0x16, 0xe9,
	0xc6, 0x73, 0xa7, 0xbd, 0xf9, 0x68, 0x31, 0xeb, 0x44, 0x1f, 0xac, 0xc8, 0x0e, 0xf4, 0x1b, 0x66,
	0xf6, 0xe1, 0xa2, 0x71, 0xeb, 0xef, 0x2f, 0xcb, 0x60, 0xd4, 0x37, 0xb9, 0x16, 0x9e, 0x3b, 0x75,
	0xe6, 0x43, 0xbf, 0xac, 0xf1, 0x13, 0x1a, 0x84, 0x4a, 0x6e, 0xb2, 0x44, 0x70, 0xaf, 0x57, 0x2e,
	0x78, 0xfc, 0xfd, 0x82, 0x64, 0x59, 0x21, 0xf7, 0xd2, 0xa4, 0xb9, 0xdf, 0x38, 0x14, 0x6e, 0x3a,
	0x55, 0x3c, 0x0b, 0x05, 0xf7, 0xfa, 0x3f, 0x76, 0x7b, 0xae, 0x90, 0xca, 0xad, 0x76, 0x98, 0x5c,
	0xa3, 0x71, 0x6b, 0x10, 0xde, 0x41, 0xbd, 0xb5, 0xb0, 0xb1, 0x87, 0x7e, 0x51, 0xe2, 0x7d, 0xf4,
	0x6f, 0xcb, 0xe2, 0xac, 0xce, 0x64, 0x1f, 0x57, 0xee, 0x85, 0x53, 0xc0, 0x2d, 0xdf, 0xdf, 0xc0,
	0x77, 0xe7, 0x2f, 0x67, 0x11, 0x98, 0x55, 0x16, 0x90, 0x50, 0x25, 0xb4, 0x4c, 0x60, 0xe0, 0x8d,
	0x0a, 0x19, 0x81, 0x14, 0x6b, 0x30, 0xb4, 0xfb, 0x9c, 0x82, 0xff, 0xe5, 0x19, 0x9d, 0x7e, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x6d, 0x68, 0x71, 0x38, 0xa9, 0x02, 0x00, 0x00,
}
