// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: github.com/dogmatiq/enginekit/enginetest/internal/testapp/events.proto

package testapp

import (
	action "github.com/dogmatiq/enginekit/enginetest/internal/action"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoActions struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Actions *[]*action.Action      `protobuf:"bytes,1,rep,name=actions"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DoActions) Reset() {
	*x = DoActions{}
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoActions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoActions) ProtoMessage() {}

func (x *DoActions) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DoActions) GetActions() []*action.Action {
	if x != nil {
		if x.xxx_hidden_Actions != nil {
			return *x.xxx_hidden_Actions
		}
	}
	return nil
}

func (x *DoActions) SetActions(v []*action.Action) {
	x.xxx_hidden_Actions = &v
}

type DoActions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Actions []*action.Action
}

func (b0 DoActions_builder) Build() *DoActions {
	m0 := &DoActions{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Actions = &b.Actions
	return m0
}

type GenericEvent struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value string                 `protobuf:"bytes,1,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GenericEvent) Reset() {
	*x = GenericEvent{}
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericEvent) ProtoMessage() {}

func (x *GenericEvent) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GenericEvent) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *GenericEvent) SetValue(v string) {
	x.xxx_hidden_Value = v
}

type GenericEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value string
}

func (b0 GenericEvent_builder) Build() *GenericEvent {
	m0 := &GenericEvent{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	return m0
}

var File_github_com_dogmatiq_enginekit_enginetest_internal_testapp_events_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_events_proto_rawDesc = "" +
	"\n" +
	"Fgithub.com/dogmatiq/enginekit/enginetest/internal/testapp/events.proto\x12\x1ddogmatiq.enginekit.enginetest\x1aEgithub.com/dogmatiq/enginekit/enginetest/internal/action/action.proto\"L\n" +
	"\tDoActions\x12?\n" +
	"\aactions\x18\x01 \x03(\v2%.dogmatiq.enginekit.enginetest.ActionR\aactions\"+\n" +
	"\fGenericEvent\x12\x1b\n" +
	"\x05value\x18\x01 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05valueB;Z9github.com/dogmatiq/enginekit/enginetest/internal/testappb\beditionsp\xe9\a"

var file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_events_proto_goTypes = []any{
	(*DoActions)(nil),     // 0: dogmatiq.enginekit.enginetest.DoActions
	(*GenericEvent)(nil),  // 1: dogmatiq.enginekit.enginetest.GenericEvent
	(*action.Action)(nil), // 2: dogmatiq.enginekit.enginetest.Action
}
var file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_events_proto_depIdxs = []int32{
	2, // 0: dogmatiq.enginekit.enginetest.DoActions.actions:type_name -> dogmatiq.enginekit.enginetest.Action
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_events_proto_init() }
func file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_events_proto_init() {
	if File_github_com_dogmatiq_enginekit_enginetest_internal_testapp_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_events_proto_rawDesc), len(file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_events_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_events_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_events_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_enginekit_enginetest_internal_testapp_events_proto = out.File
	file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_events_proto_goTypes = nil
	file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_events_proto_depIdxs = nil
}
