// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: github.com/dogmatiq/enginekit/enginetest/internal/testapp/integration.proto

package testapp

import (
	action "github.com/dogmatiq/enginekit/enginetest/internal/action"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntegrationCommandA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsInvalid     bool                   `protobuf:"varint,1,opt,name=is_invalid,json=isInvalid,proto3" json:"is_invalid,omitempty"`
	Actions       []*action.Action       `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationCommandA) Reset() {
	*x = IntegrationCommandA{}
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationCommandA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationCommandA) ProtoMessage() {}

func (x *IntegrationCommandA) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationCommandA.ProtoReflect.Descriptor instead.
func (*IntegrationCommandA) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_rawDescGZIP(), []int{0}
}

func (x *IntegrationCommandA) GetIsInvalid() bool {
	if x != nil {
		return x.IsInvalid
	}
	return false
}

func (x *IntegrationCommandA) GetActions() []*action.Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type IntegrationCommandB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsInvalid     bool                   `protobuf:"varint,1,opt,name=is_invalid,json=isInvalid,proto3" json:"is_invalid,omitempty"`
	Actions       []*action.Action       `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationCommandB) Reset() {
	*x = IntegrationCommandB{}
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationCommandB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationCommandB) ProtoMessage() {}

func (x *IntegrationCommandB) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationCommandB.ProtoReflect.Descriptor instead.
func (*IntegrationCommandB) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_rawDescGZIP(), []int{1}
}

func (x *IntegrationCommandB) GetIsInvalid() bool {
	if x != nil {
		return x.IsInvalid
	}
	return false
}

func (x *IntegrationCommandB) GetActions() []*action.Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type IntegrationEventA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationEventA) Reset() {
	*x = IntegrationEventA{}
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationEventA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationEventA) ProtoMessage() {}

func (x *IntegrationEventA) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationEventA.ProtoReflect.Descriptor instead.
func (*IntegrationEventA) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_rawDescGZIP(), []int{2}
}

func (x *IntegrationEventA) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type IntegrationEventB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationEventB) Reset() {
	*x = IntegrationEventB{}
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationEventB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationEventB) ProtoMessage() {}

func (x *IntegrationEventB) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationEventB.ProtoReflect.Descriptor instead.
func (*IntegrationEventB) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_rawDescGZIP(), []int{3}
}

func (x *IntegrationEventB) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_rawDesc = "" +
	"\n" +
	"Kgithub.com/dogmatiq/enginekit/enginetest/internal/testapp/integration.proto\x12\x1ddogmatiq.enginekit.enginetest\x1aEgithub.com/dogmatiq/enginekit/enginetest/internal/action/action.proto\"u\n" +
	"\x13IntegrationCommandA\x12\x1d\n" +
	"\n" +
	"is_invalid\x18\x01 \x01(\bR\tisInvalid\x12?\n" +
	"\aactions\x18\x02 \x03(\v2%.dogmatiq.enginekit.enginetest.ActionR\aactions\"u\n" +
	"\x13IntegrationCommandB\x12\x1d\n" +
	"\n" +
	"is_invalid\x18\x01 \x01(\bR\tisInvalid\x12?\n" +
	"\aactions\x18\x02 \x03(\v2%.dogmatiq.enginekit.enginetest.ActionR\aactions\")\n" +
	"\x11IntegrationEventA\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\")\n" +
	"\x11IntegrationEventB\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueB;Z9github.com/dogmatiq/enginekit/enginetest/internal/testappb\x06proto3"

var (
	file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_rawDescData []byte
)

func file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_rawDesc), len(file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_rawDescData
}

var file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_goTypes = []any{
	(*IntegrationCommandA)(nil), // 0: dogmatiq.enginekit.enginetest.IntegrationCommandA
	(*IntegrationCommandB)(nil), // 1: dogmatiq.enginekit.enginetest.IntegrationCommandB
	(*IntegrationEventA)(nil),   // 2: dogmatiq.enginekit.enginetest.IntegrationEventA
	(*IntegrationEventB)(nil),   // 3: dogmatiq.enginekit.enginetest.IntegrationEventB
	(*action.Action)(nil),       // 4: dogmatiq.enginekit.enginetest.Action
}
var file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_depIdxs = []int32{
	4, // 0: dogmatiq.enginekit.enginetest.IntegrationCommandA.actions:type_name -> dogmatiq.enginekit.enginetest.Action
	4, // 1: dogmatiq.enginekit.enginetest.IntegrationCommandB.actions:type_name -> dogmatiq.enginekit.enginetest.Action
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_init() }
func file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_init() {
	if File_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_rawDesc), len(file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto = out.File
	file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_goTypes = nil
	file_github_com_dogmatiq_enginekit_enginetest_internal_testapp_integration_proto_depIdxs = nil
}
