// Code generated by protoc-gen-go-primo. DO NOT EDIT.
// versions:
// 	protoc-gen-go-primo v
// 	protoc              v6.33.1
// source: github.com/dogmatiq/enginekit/protobuf/uuidpb/uuid.proto

package uuidpb

import proto "google.golang.org/protobuf/proto"

type UUIDBuilder struct {
	prototype UUID
}

// NewUUIDBuilder returns a builder that constructs [UUID] messages.
func NewUUIDBuilder() *UUIDBuilder {
	return &UUIDBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *UUIDBuilder) From(x *UUID) *UUIDBuilder {
	proto.Reset(&b.prototype)
	b.prototype.SetUpper(x.GetUpper())
	b.prototype.SetLower(x.GetLower())
	return b
}

// Build returns a new [UUID] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *UUIDBuilder) Build() *UUID {
	m := &UUID{}
	m.SetUpper(b.prototype.GetUpper())
	m.SetLower(b.prototype.GetLower())
	return m
}

// WithUpper configures the builder to set the Upper field to v,
// then returns b.
func (b *UUIDBuilder) WithUpper(v uint64) *UUIDBuilder {
	b.prototype.SetUpper(v)
	return b
}

// WithLower configures the builder to set the Lower field to v,
// then returns b.
func (b *UUIDBuilder) WithLower(v uint64) *UUIDBuilder {
	b.prototype.SetLower(v)
	return b
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*UUID] to implement [encoding.BinaryMarshaler].
func (x *UUID) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*UUID] to implement [encoding.BinaryUnmarshaler].
func (x *UUID) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}
