// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: github.com/dogmatiq/enginekit/protobuf/identitypb/identity.proto

package identitypb

import (
	uuidpb "github.com/dogmatiq/enginekit/protobuf/uuidpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Identity represents the identity of an entity.
//
// It is used to identify Dogma applications, handlers, sites, streams, etc.
type Identity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the entity's human-readable name.
	//
	// The name should be unique enough to allow a human to identify the entity
	// without ambiguity. There is no hard requirement for uniqueness.
	//
	// Entity names may be changed at any time.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Key is the entity's immutable, unique key.
	//
	// The key is used to uniquely identify the entity globally, and across all
	// time. Every entity must have its own UUID, which must not be changed.
	Key           *uuidpb.UUID `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_rawDescGZIP(), []int{0}
}

func (x *Identity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Identity) GetKey() *uuidpb.UUID {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_rawDesc = "" +
	"\n" +
	"@github.com/dogmatiq/enginekit/protobuf/identitypb/identity.proto\x12\x0edogma.protobuf\x1a8github.com/dogmatiq/enginekit/protobuf/uuidpb/uuid.proto\"F\n" +
	"\bIdentity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x03key\x18\x02 \x01(\v2\x14.dogma.protobuf.UUIDR\x03keyB3Z1github.com/dogmatiq/enginekit/protobuf/identitypbb\x06proto3"

var (
	file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_rawDescData []byte
)

func file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_rawDesc), len(file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_rawDescData
}

var file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_goTypes = []any{
	(*Identity)(nil),    // 0: dogma.protobuf.Identity
	(*uuidpb.UUID)(nil), // 1: dogma.protobuf.UUID
}
var file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_depIdxs = []int32{
	1, // 0: dogma.protobuf.Identity.key:type_name -> dogma.protobuf.UUID
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_init() }
func file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_init() {
	if File_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_rawDesc), len(file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto = out.File
	file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_goTypes = nil
	file_github_com_dogmatiq_enginekit_protobuf_identitypb_identity_proto_depIdxs = nil
}
