// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: github.com/dogmatiq/enginekit/protobuf/envelopepb/envelope.proto

package envelopepb

import (
	identitypb "github.com/dogmatiq/enginekit/protobuf/identitypb"
	uuidpb "github.com/dogmatiq/enginekit/protobuf/uuidpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope is a container for a Dogma message and its meta-data.
//
// It is wire-compatible with [MultiEnvelope].
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body          *Body                  `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Envelope) GetBody() *Body {
	if x != nil {
		return x.Body
	}
	return nil
}

// MultiEnvelope is an efficient encoding of an ordered sequence of [Envelope]
// values that share common header context.
type MultiEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Bodies        []*Body                `protobuf:"bytes,2,rep,name=bodies,proto3" json:"bodies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiEnvelope) Reset() {
	*x = MultiEnvelope{}
	mi := &file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiEnvelope) ProtoMessage() {}

func (x *MultiEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiEnvelope.ProtoReflect.Descriptor instead.
func (*MultiEnvelope) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *MultiEnvelope) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *MultiEnvelope) GetBodies() []*Body {
	if x != nil {
		return x.Bodies
	}
	return nil
}

// Source identifies where a message originated.
type Source struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Site is the (optional) identity of the "site" that the source
	// application is running within.
	//
	// The site is used to disambiguate between messages from different
	// installations of the same application.
	Site *identitypb.Identity `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	// Application is the identity of the Dogma application that produced the
	// message.
	Application *identitypb.Identity `protobuf:"bytes,2,opt,name=application,proto3" json:"application,omitempty"`
	// Handler is the identity of the Dogma handler that produced the message.
	//
	// It is the zero-value if the message was not produced by a handler.
	Handler *identitypb.Identity `protobuf:"bytes,3,opt,name=handler,proto3" json:"handler,omitempty"`
	// InstanceId is the ID of the aggregate or process instance that produced
	// the message.
	//
	// It is empty if the message was not produced by an aggregate or process
	// handler.
	InstanceId    string `protobuf:"bytes,4,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *Source) GetSite() *identitypb.Identity {
	if x != nil {
		return x.Site
	}
	return nil
}

func (x *Source) GetApplication() *identitypb.Identity {
	if x != nil {
		return x.Application
	}
	return nil
}

func (x *Source) GetHandler() *identitypb.Identity {
	if x != nil {
		return x.Handler
	}
	return nil
}

func (x *Source) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// Message is the serialized representation of a [dogma.Message].
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TypeId is a unique identifier for the type of message, as per the Dogma
	// message type registry.
	TypeId *uuidpb.UUID `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	// Description is a human-readable description of the message, as returned by
	// the [dogma.Message.MessageDescription] method.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Data is the binary message data obtained by calling
	// [dogma.Message.MarshalBinary] on the message.
	Data          []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetTypeId() *uuidpb.UUID {
	if x != nil {
		return x.TypeId
	}
	return nil
}

func (x *Message) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Header struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CausationId is the (optional) ID of the message that was the direct cause
	// of the messages.
	//
	// If it is the zero-value, the messages were not caused by any other
	// message.
	CausationId *uuidpb.UUID `protobuf:"bytes,1,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	// CorrelationId is the (optional) ID of the first ancestor of the messages
	// that was itself not caused by another message, that is, it's the root of
	// the message chain that ultimately resulted in these messages.
	//
	// If it is the zero-value, the messages were not caused by any other
	// message.
	CorrelationId *uuidpb.UUID `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Source identifies the origin of the messages.
	Source *Source `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// Extensions is a set of extension values associated with the messages,
	// their causal chain, or the envelope itself.
	Extensions []*anypb.Any `protobuf:"bytes,4,rep,name=extensions,proto3" json:"extensions,omitempty"`
	// Baggage is a set of extension values that are propagated through the
	// entire causal chain of messages.
	Baggage       []*anypb.Any `protobuf:"bytes,5,rep,name=baggage,proto3" json:"baggage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_rawDescGZIP(), []int{4}
}

func (x *Header) GetCausationId() *uuidpb.UUID {
	if x != nil {
		return x.CausationId
	}
	return nil
}

func (x *Header) GetCorrelationId() *uuidpb.UUID {
	if x != nil {
		return x.CorrelationId
	}
	return nil
}

func (x *Header) GetSource() *Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Header) GetExtensions() []*anypb.Any {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *Header) GetBaggage() []*anypb.Any {
	if x != nil {
		return x.Baggage
	}
	return nil
}

// Body contains the metadata and encoded form of a single message in an
// [Envelope] or [MultiEnvelope].
type Body struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MessageId is a unique identifier for the message in this envelope.
	MessageId *uuidpb.UUID `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// IdempotencyKey is an application-defined value used to identify a command
	// across retries.
	//
	// It is the zero-value if the message is not a command, or if the producer
	// of the message did not provide an idempotency key.
	IdempotencyKey string `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// CreatedAt is the time at which the envelope was created.
	//
	// This is typically the point at which the message first enters the engine.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// ScheduledFor is the time at which a timeout message is scheduled to occur.
	//
	// It is the zero-value if the message is a command or event.
	ScheduledFor *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=scheduled_for,json=scheduledFor,proto3" json:"scheduled_for,omitempty"`
	// Message is the encoded representation of the [dogma.Message].
	Message *Message `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	// Extensions is a set of extension values associated with this message.
	//
	// Any values in [Header.Extensions] are overridden by values in this field
	// that have the same type URL.
	Extensions []*anypb.Any `protobuf:"bytes,6,rep,name=extensions,proto3" json:"extensions,omitempty"`
	// Baggage is a set of extension values associated with this message and/or
	// its causal chain.
	//
	// Any values in [Header.Baggage] are overridden by values in this field
	// that have the same type URL.
	Baggage       []*anypb.Any `protobuf:"bytes,7,rep,name=baggage,proto3" json:"baggage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Body) Reset() {
	*x = Body{}
	mi := &file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Body) ProtoMessage() {}

func (x *Body) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Body.ProtoReflect.Descriptor instead.
func (*Body) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_rawDescGZIP(), []int{5}
}

func (x *Body) GetMessageId() *uuidpb.UUID {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *Body) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Body) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Body) GetScheduledFor() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledFor
	}
	return nil
}

func (x *Body) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Body) GetExtensions() []*anypb.Any {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *Body) GetBaggage() []*anypb.Any {
	if x != nil {
		return x.Baggage
	}
	return nil
}

var File_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_rawDesc = "" +
	"\n" +
	"@github.com/dogmatiq/enginekit/protobuf/envelopepb/envelope.proto\x12\x0edogma.protobuf\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\x1a@github.com/dogmatiq/enginekit/protobuf/identitypb/identity.proto\x1a8github.com/dogmatiq/enginekit/protobuf/uuidpb/uuid.proto\"d\n" +
	"\bEnvelope\x12.\n" +
	"\x06header\x18\x01 \x01(\v2\x16.dogma.protobuf.HeaderR\x06header\x12(\n" +
	"\x04body\x18\x02 \x01(\v2\x14.dogma.protobuf.BodyR\x04body\"m\n" +
	"\rMultiEnvelope\x12.\n" +
	"\x06header\x18\x01 \x01(\v2\x16.dogma.protobuf.HeaderR\x06header\x12,\n" +
	"\x06bodies\x18\x02 \x03(\v2\x14.dogma.protobuf.BodyR\x06bodies\"\xc7\x01\n" +
	"\x06Source\x12,\n" +
	"\x04site\x18\x01 \x01(\v2\x18.dogma.protobuf.IdentityR\x04site\x12:\n" +
	"\vapplication\x18\x02 \x01(\v2\x18.dogma.protobuf.IdentityR\vapplication\x122\n" +
	"\ahandler\x18\x03 \x01(\v2\x18.dogma.protobuf.IdentityR\ahandler\x12\x1f\n" +
	"\vinstance_id\x18\x04 \x01(\tR\n" +
	"instanceId\"n\n" +
	"\aMessage\x12-\n" +
	"\atype_id\x18\x01 \x01(\v2\x14.dogma.protobuf.UUIDR\x06typeId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x94\x02\n" +
	"\x06Header\x127\n" +
	"\fcausation_id\x18\x01 \x01(\v2\x14.dogma.protobuf.UUIDR\vcausationId\x12;\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\v2\x14.dogma.protobuf.UUIDR\rcorrelationId\x12.\n" +
	"\x06source\x18\x03 \x01(\v2\x16.dogma.protobuf.SourceR\x06source\x124\n" +
	"\n" +
	"extensions\x18\x04 \x03(\v2\x14.google.protobuf.AnyR\n" +
	"extensions\x12.\n" +
	"\abaggage\x18\x05 \x03(\v2\x14.google.protobuf.AnyR\abaggage\"\xf9\x02\n" +
	"\x04Body\x123\n" +
	"\n" +
	"message_id\x18\x01 \x01(\v2\x14.dogma.protobuf.UUIDR\tmessageId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12?\n" +
	"\rscheduled_for\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fscheduledFor\x121\n" +
	"\amessage\x18\x05 \x01(\v2\x17.dogma.protobuf.MessageR\amessage\x124\n" +
	"\n" +
	"extensions\x18\x06 \x03(\v2\x14.google.protobuf.AnyR\n" +
	"extensions\x12.\n" +
	"\abaggage\x18\a \x03(\v2\x14.google.protobuf.AnyR\abaggageB3Z1github.com/dogmatiq/enginekit/protobuf/envelopepbb\x06proto3"

var (
	file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_rawDescData []byte
)

func file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_rawDesc), len(file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_rawDescData
}

var file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_goTypes = []any{
	(*Envelope)(nil),              // 0: dogma.protobuf.Envelope
	(*MultiEnvelope)(nil),         // 1: dogma.protobuf.MultiEnvelope
	(*Source)(nil),                // 2: dogma.protobuf.Source
	(*Message)(nil),               // 3: dogma.protobuf.Message
	(*Header)(nil),                // 4: dogma.protobuf.Header
	(*Body)(nil),                  // 5: dogma.protobuf.Body
	(*identitypb.Identity)(nil),   // 6: dogma.protobuf.Identity
	(*uuidpb.UUID)(nil),           // 7: dogma.protobuf.UUID
	(*anypb.Any)(nil),             // 8: google.protobuf.Any
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_depIdxs = []int32{
	4,  // 0: dogma.protobuf.Envelope.header:type_name -> dogma.protobuf.Header
	5,  // 1: dogma.protobuf.Envelope.body:type_name -> dogma.protobuf.Body
	4,  // 2: dogma.protobuf.MultiEnvelope.header:type_name -> dogma.protobuf.Header
	5,  // 3: dogma.protobuf.MultiEnvelope.bodies:type_name -> dogma.protobuf.Body
	6,  // 4: dogma.protobuf.Source.site:type_name -> dogma.protobuf.Identity
	6,  // 5: dogma.protobuf.Source.application:type_name -> dogma.protobuf.Identity
	6,  // 6: dogma.protobuf.Source.handler:type_name -> dogma.protobuf.Identity
	7,  // 7: dogma.protobuf.Message.type_id:type_name -> dogma.protobuf.UUID
	7,  // 8: dogma.protobuf.Header.causation_id:type_name -> dogma.protobuf.UUID
	7,  // 9: dogma.protobuf.Header.correlation_id:type_name -> dogma.protobuf.UUID
	2,  // 10: dogma.protobuf.Header.source:type_name -> dogma.protobuf.Source
	8,  // 11: dogma.protobuf.Header.extensions:type_name -> google.protobuf.Any
	8,  // 12: dogma.protobuf.Header.baggage:type_name -> google.protobuf.Any
	7,  // 13: dogma.protobuf.Body.message_id:type_name -> dogma.protobuf.UUID
	9,  // 14: dogma.protobuf.Body.created_at:type_name -> google.protobuf.Timestamp
	9,  // 15: dogma.protobuf.Body.scheduled_for:type_name -> google.protobuf.Timestamp
	3,  // 16: dogma.protobuf.Body.message:type_name -> dogma.protobuf.Message
	8,  // 17: dogma.protobuf.Body.extensions:type_name -> google.protobuf.Any
	8,  // 18: dogma.protobuf.Body.baggage:type_name -> google.protobuf.Any
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_init() }
func file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_init() {
	if File_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_rawDesc), len(file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto = out.File
	file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_goTypes = nil
	file_github_com_dogmatiq_enginekit_protobuf_envelopepb_envelope_proto_depIdxs = nil
}
