// Code generated by protoc-gen-go-primo. DO NOT EDIT.
// versions:
// 	protoc-gen-go-primo v
// 	protoc              v6.33.1
// source: github.com/dogmatiq/enginekit/protobuf/envelopepb/envelope.proto

package envelopepb

import (
	identitypb "github.com/dogmatiq/enginekit/protobuf/identitypb"
	uuidpb "github.com/dogmatiq/enginekit/protobuf/uuidpb"
	proto "google.golang.org/protobuf/proto"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

type EnvelopeBuilder struct {
	prototype Envelope
}

// NewEnvelopeBuilder returns a builder that constructs [Envelope] messages.
func NewEnvelopeBuilder() *EnvelopeBuilder {
	return &EnvelopeBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *EnvelopeBuilder) From(x *Envelope) *EnvelopeBuilder {
	proto.Reset(&b.prototype)
	if x.HasHeader() {
		b.prototype.SetHeader(x.GetHeader())
	}
	if x.HasBody() {
		b.prototype.SetBody(x.GetBody())
	}
	return b
}

// Build returns a new [Envelope] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *EnvelopeBuilder) Build() *Envelope {
	m := &Envelope{}
	if b.prototype.HasHeader() {
		m.SetHeader(b.prototype.GetHeader())
	}
	if b.prototype.HasBody() {
		m.SetBody(b.prototype.GetBody())
	}
	return m
}

// WithHeader configures the builder to set the Header field to v,
// then returns b.
func (b *EnvelopeBuilder) WithHeader(v *Header) *EnvelopeBuilder {
	b.prototype.SetHeader(v)
	return b
}

// WithBody configures the builder to set the Body field to v,
// then returns b.
func (b *EnvelopeBuilder) WithBody(v *Body) *EnvelopeBuilder {
	b.prototype.SetBody(v)
	return b
}

type MultiEnvelopeBuilder struct {
	prototype MultiEnvelope
}

// NewMultiEnvelopeBuilder returns a builder that constructs [MultiEnvelope] messages.
func NewMultiEnvelopeBuilder() *MultiEnvelopeBuilder {
	return &MultiEnvelopeBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *MultiEnvelopeBuilder) From(x *MultiEnvelope) *MultiEnvelopeBuilder {
	proto.Reset(&b.prototype)
	if x.HasHeader() {
		b.prototype.SetHeader(x.GetHeader())
	}
	b.prototype.SetBodies(x.GetBodies())
	return b
}

// Build returns a new [MultiEnvelope] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *MultiEnvelopeBuilder) Build() *MultiEnvelope {
	m := &MultiEnvelope{}
	if b.prototype.HasHeader() {
		m.SetHeader(b.prototype.GetHeader())
	}
	m.SetBodies(b.prototype.GetBodies())
	return m
}

// WithHeader configures the builder to set the Header field to v,
// then returns b.
func (b *MultiEnvelopeBuilder) WithHeader(v *Header) *MultiEnvelopeBuilder {
	b.prototype.SetHeader(v)
	return b
}

// WithBodies configures the builder to set the Bodies field to v,
// then returns b.
func (b *MultiEnvelopeBuilder) WithBodies(v []*Body) *MultiEnvelopeBuilder {
	b.prototype.SetBodies(v)
	return b
}

type SourceBuilder struct {
	prototype Source
}

// NewSourceBuilder returns a builder that constructs [Source] messages.
func NewSourceBuilder() *SourceBuilder {
	return &SourceBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *SourceBuilder) From(x *Source) *SourceBuilder {
	proto.Reset(&b.prototype)
	if x.HasSite() {
		b.prototype.SetSite(x.GetSite())
	}
	if x.HasApplication() {
		b.prototype.SetApplication(x.GetApplication())
	}
	if x.HasHandler() {
		b.prototype.SetHandler(x.GetHandler())
	}
	b.prototype.SetInstanceId(x.GetInstanceId())
	return b
}

// Build returns a new [Source] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *SourceBuilder) Build() *Source {
	m := &Source{}
	if b.prototype.HasSite() {
		m.SetSite(b.prototype.GetSite())
	}
	if b.prototype.HasApplication() {
		m.SetApplication(b.prototype.GetApplication())
	}
	if b.prototype.HasHandler() {
		m.SetHandler(b.prototype.GetHandler())
	}
	m.SetInstanceId(b.prototype.GetInstanceId())
	return m
}

// WithSite configures the builder to set the Site field to v,
// then returns b.
func (b *SourceBuilder) WithSite(v *identitypb.Identity) *SourceBuilder {
	b.prototype.SetSite(v)
	return b
}

// WithApplication configures the builder to set the Application field to v,
// then returns b.
func (b *SourceBuilder) WithApplication(v *identitypb.Identity) *SourceBuilder {
	b.prototype.SetApplication(v)
	return b
}

// WithHandler configures the builder to set the Handler field to v,
// then returns b.
func (b *SourceBuilder) WithHandler(v *identitypb.Identity) *SourceBuilder {
	b.prototype.SetHandler(v)
	return b
}

// WithInstanceId configures the builder to set the InstanceId field to v,
// then returns b.
func (b *SourceBuilder) WithInstanceId(v string) *SourceBuilder {
	b.prototype.SetInstanceId(v)
	return b
}

type MessageBuilder struct {
	prototype Message
}

// NewMessageBuilder returns a builder that constructs [Message] messages.
func NewMessageBuilder() *MessageBuilder {
	return &MessageBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *MessageBuilder) From(x *Message) *MessageBuilder {
	proto.Reset(&b.prototype)
	if x.HasTypeId() {
		b.prototype.SetTypeId(x.GetTypeId())
	}
	b.prototype.SetDescription(x.GetDescription())
	b.prototype.SetData(x.GetData())
	return b
}

// Build returns a new [Message] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *MessageBuilder) Build() *Message {
	m := &Message{}
	if b.prototype.HasTypeId() {
		m.SetTypeId(b.prototype.GetTypeId())
	}
	m.SetDescription(b.prototype.GetDescription())
	m.SetData(b.prototype.GetData())
	return m
}

// WithTypeId configures the builder to set the TypeId field to v,
// then returns b.
func (b *MessageBuilder) WithTypeId(v *uuidpb.UUID) *MessageBuilder {
	b.prototype.SetTypeId(v)
	return b
}

// WithDescription configures the builder to set the Description field to v,
// then returns b.
func (b *MessageBuilder) WithDescription(v string) *MessageBuilder {
	b.prototype.SetDescription(v)
	return b
}

// WithData configures the builder to set the Data field to v,
// then returns b.
func (b *MessageBuilder) WithData(v []byte) *MessageBuilder {
	b.prototype.SetData(v)
	return b
}

type HeaderBuilder struct {
	prototype Header
}

// NewHeaderBuilder returns a builder that constructs [Header] messages.
func NewHeaderBuilder() *HeaderBuilder {
	return &HeaderBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *HeaderBuilder) From(x *Header) *HeaderBuilder {
	proto.Reset(&b.prototype)
	if x.HasCausationId() {
		b.prototype.SetCausationId(x.GetCausationId())
	}
	if x.HasCorrelationId() {
		b.prototype.SetCorrelationId(x.GetCorrelationId())
	}
	if x.HasSource() {
		b.prototype.SetSource(x.GetSource())
	}
	b.prototype.SetExtensions(x.GetExtensions())
	b.prototype.SetBaggage(x.GetBaggage())
	return b
}

// Build returns a new [Header] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *HeaderBuilder) Build() *Header {
	m := &Header{}
	if b.prototype.HasCausationId() {
		m.SetCausationId(b.prototype.GetCausationId())
	}
	if b.prototype.HasCorrelationId() {
		m.SetCorrelationId(b.prototype.GetCorrelationId())
	}
	if b.prototype.HasSource() {
		m.SetSource(b.prototype.GetSource())
	}
	m.SetExtensions(b.prototype.GetExtensions())
	m.SetBaggage(b.prototype.GetBaggage())
	return m
}

// WithCausationId configures the builder to set the CausationId field to v,
// then returns b.
func (b *HeaderBuilder) WithCausationId(v *uuidpb.UUID) *HeaderBuilder {
	b.prototype.SetCausationId(v)
	return b
}

// WithCorrelationId configures the builder to set the CorrelationId field to v,
// then returns b.
func (b *HeaderBuilder) WithCorrelationId(v *uuidpb.UUID) *HeaderBuilder {
	b.prototype.SetCorrelationId(v)
	return b
}

// WithSource configures the builder to set the Source field to v,
// then returns b.
func (b *HeaderBuilder) WithSource(v *Source) *HeaderBuilder {
	b.prototype.SetSource(v)
	return b
}

// WithExtensions configures the builder to set the Extensions field to v,
// then returns b.
func (b *HeaderBuilder) WithExtensions(v []*anypb.Any) *HeaderBuilder {
	b.prototype.SetExtensions(v)
	return b
}

// WithBaggage configures the builder to set the Baggage field to v,
// then returns b.
func (b *HeaderBuilder) WithBaggage(v []*anypb.Any) *HeaderBuilder {
	b.prototype.SetBaggage(v)
	return b
}

type BodyBuilder struct {
	prototype Body
}

// NewBodyBuilder returns a builder that constructs [Body] messages.
func NewBodyBuilder() *BodyBuilder {
	return &BodyBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *BodyBuilder) From(x *Body) *BodyBuilder {
	proto.Reset(&b.prototype)
	if x.HasMessageId() {
		b.prototype.SetMessageId(x.GetMessageId())
	}
	b.prototype.SetIdempotencyKey(x.GetIdempotencyKey())
	if x.HasCreatedAt() {
		b.prototype.SetCreatedAt(x.GetCreatedAt())
	}
	if x.HasScheduledFor() {
		b.prototype.SetScheduledFor(x.GetScheduledFor())
	}
	if x.HasMessage() {
		b.prototype.SetMessage(x.GetMessage())
	}
	b.prototype.SetExtensions(x.GetExtensions())
	b.prototype.SetBaggage(x.GetBaggage())
	return b
}

// Build returns a new [Body] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *BodyBuilder) Build() *Body {
	m := &Body{}
	if b.prototype.HasMessageId() {
		m.SetMessageId(b.prototype.GetMessageId())
	}
	m.SetIdempotencyKey(b.prototype.GetIdempotencyKey())
	if b.prototype.HasCreatedAt() {
		m.SetCreatedAt(b.prototype.GetCreatedAt())
	}
	if b.prototype.HasScheduledFor() {
		m.SetScheduledFor(b.prototype.GetScheduledFor())
	}
	if b.prototype.HasMessage() {
		m.SetMessage(b.prototype.GetMessage())
	}
	m.SetExtensions(b.prototype.GetExtensions())
	m.SetBaggage(b.prototype.GetBaggage())
	return m
}

// WithMessageId configures the builder to set the MessageId field to v,
// then returns b.
func (b *BodyBuilder) WithMessageId(v *uuidpb.UUID) *BodyBuilder {
	b.prototype.SetMessageId(v)
	return b
}

// WithIdempotencyKey configures the builder to set the IdempotencyKey field to v,
// then returns b.
func (b *BodyBuilder) WithIdempotencyKey(v string) *BodyBuilder {
	b.prototype.SetIdempotencyKey(v)
	return b
}

// WithCreatedAt configures the builder to set the CreatedAt field to v,
// then returns b.
func (b *BodyBuilder) WithCreatedAt(v *timestamppb.Timestamp) *BodyBuilder {
	b.prototype.SetCreatedAt(v)
	return b
}

// WithScheduledFor configures the builder to set the ScheduledFor field to v,
// then returns b.
func (b *BodyBuilder) WithScheduledFor(v *timestamppb.Timestamp) *BodyBuilder {
	b.prototype.SetScheduledFor(v)
	return b
}

// WithMessage configures the builder to set the Message field to v,
// then returns b.
func (b *BodyBuilder) WithMessage(v *Message) *BodyBuilder {
	b.prototype.SetMessage(v)
	return b
}

// WithExtensions configures the builder to set the Extensions field to v,
// then returns b.
func (b *BodyBuilder) WithExtensions(v []*anypb.Any) *BodyBuilder {
	b.prototype.SetExtensions(v)
	return b
}

// WithBaggage configures the builder to set the Baggage field to v,
// then returns b.
func (b *BodyBuilder) WithBaggage(v []*anypb.Any) *BodyBuilder {
	b.prototype.SetBaggage(v)
	return b
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*Envelope] to implement [encoding.BinaryMarshaler].
func (x *Envelope) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*Envelope] to implement [encoding.BinaryUnmarshaler].
func (x *Envelope) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*MultiEnvelope] to implement [encoding.BinaryMarshaler].
func (x *MultiEnvelope) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*MultiEnvelope] to implement [encoding.BinaryUnmarshaler].
func (x *MultiEnvelope) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*Source] to implement [encoding.BinaryMarshaler].
func (x *Source) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*Source] to implement [encoding.BinaryUnmarshaler].
func (x *Source) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*Message] to implement [encoding.BinaryMarshaler].
func (x *Message) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*Message] to implement [encoding.BinaryUnmarshaler].
func (x *Message) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*Header] to implement [encoding.BinaryMarshaler].
func (x *Header) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*Header] to implement [encoding.BinaryUnmarshaler].
func (x *Header) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*Body] to implement [encoding.BinaryMarshaler].
func (x *Body) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*Body] to implement [encoding.BinaryUnmarshaler].
func (x *Body) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}
