// Code generated by protoc-gen-go-primo. DO NOT EDIT.
// versions:
// 	protoc-gen-go-primo v
// 	protoc              v6.33.1
// source: github.com/dogmatiq/enginekit/protobuf/envelopepb/extensions.proto

package envelopepb

import (
	uuidpb "github.com/dogmatiq/enginekit/protobuf/uuidpb"
	proto "google.golang.org/protobuf/proto"
)

type EventStreamPositionBuilder struct {
	prototype EventStreamPosition
}

// NewEventStreamPositionBuilder returns a builder that constructs [EventStreamPosition] messages.
func NewEventStreamPositionBuilder() *EventStreamPositionBuilder {
	return &EventStreamPositionBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *EventStreamPositionBuilder) From(x *EventStreamPosition) *EventStreamPositionBuilder {
	proto.Reset(&b.prototype)
	if x.HasStreamId() {
		b.prototype.SetStreamId(x.GetStreamId())
	}
	b.prototype.SetOffset(x.GetOffset())
	return b
}

// Build returns a new [EventStreamPosition] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *EventStreamPositionBuilder) Build() *EventStreamPosition {
	m := &EventStreamPosition{}
	if b.prototype.HasStreamId() {
		m.SetStreamId(b.prototype.GetStreamId())
	}
	m.SetOffset(b.prototype.GetOffset())
	return m
}

// WithStreamId configures the builder to set the StreamId field to v,
// then returns b.
func (b *EventStreamPositionBuilder) WithStreamId(v *uuidpb.UUID) *EventStreamPositionBuilder {
	b.prototype.SetStreamId(v)
	return b
}

// WithOffset configures the builder to set the Offset field to v,
// then returns b.
func (b *EventStreamPositionBuilder) WithOffset(v uint64) *EventStreamPositionBuilder {
	b.prototype.SetOffset(v)
	return b
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*EventStreamPosition] to implement [encoding.BinaryMarshaler].
func (x *EventStreamPosition) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*EventStreamPosition] to implement [encoding.BinaryUnmarshaler].
func (x *EventStreamPosition) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}
