// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: github.com/dogmatiq/enginekit/protobuf/envelopepb/extensions.proto

package envelopepb

import (
	uuidpb "github.com/dogmatiq/enginekit/protobuf/uuidpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventStreamPosition is an extension value for an [Envelope] that identifies
// the stream from which an event was obtained, and the offset of the event
// within that stream.
type EventStreamPosition struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_StreamId *uuidpb.UUID           `protobuf:"bytes,1,opt,name=stream_id,json=streamId"`
	xxx_hidden_Offset   uint64                 `protobuf:"varint,2,opt,name=offset"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EventStreamPosition) Reset() {
	*x = EventStreamPosition{}
	mi := &file_github_com_dogmatiq_enginekit_protobuf_envelopepb_extensions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStreamPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStreamPosition) ProtoMessage() {}

func (x *EventStreamPosition) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_enginekit_protobuf_envelopepb_extensions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventStreamPosition) GetStreamId() *uuidpb.UUID {
	if x != nil {
		return x.xxx_hidden_StreamId
	}
	return nil
}

func (x *EventStreamPosition) GetOffset() uint64 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *EventStreamPosition) SetStreamId(v *uuidpb.UUID) {
	x.xxx_hidden_StreamId = v
}

func (x *EventStreamPosition) SetOffset(v uint64) {
	x.xxx_hidden_Offset = v
}

func (x *EventStreamPosition) HasStreamId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StreamId != nil
}

func (x *EventStreamPosition) ClearStreamId() {
	x.xxx_hidden_StreamId = nil
}

type EventStreamPosition_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// StreamId is the identifier of the stream within which the event was
	// recorded.
	StreamId *uuidpb.UUID
	// Offset is the position of the event within the stream. The first event is
	// at offset zero.
	Offset uint64
}

func (b0 EventStreamPosition_builder) Build() *EventStreamPosition {
	m0 := &EventStreamPosition{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_StreamId = b.StreamId
	x.xxx_hidden_Offset = b.Offset
	return m0
}

var File_github_com_dogmatiq_enginekit_protobuf_envelopepb_extensions_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_enginekit_protobuf_envelopepb_extensions_proto_rawDesc = "" +
	"\n" +
	"Bgithub.com/dogmatiq/enginekit/protobuf/envelopepb/extensions.proto\x12\x0edogma.protobuf\x1a8github.com/dogmatiq/enginekit/protobuf/uuidpb/uuid.proto\"g\n" +
	"\x13EventStreamPosition\x121\n" +
	"\tstream_id\x18\x01 \x01(\v2\x14.dogma.protobuf.UUIDR\bstreamId\x12\x1d\n" +
	"\x06offset\x18\x02 \x01(\x04B\x05\xaa\x01\x02\b\x02R\x06offsetB3Z1github.com/dogmatiq/enginekit/protobuf/envelopepbb\beditionsp\xe9\a"

var file_github_com_dogmatiq_enginekit_protobuf_envelopepb_extensions_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_dogmatiq_enginekit_protobuf_envelopepb_extensions_proto_goTypes = []any{
	(*EventStreamPosition)(nil), // 0: dogma.protobuf.EventStreamPosition
	(*uuidpb.UUID)(nil),         // 1: dogma.protobuf.UUID
}
var file_github_com_dogmatiq_enginekit_protobuf_envelopepb_extensions_proto_depIdxs = []int32{
	1, // 0: dogma.protobuf.EventStreamPosition.stream_id:type_name -> dogma.protobuf.UUID
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_enginekit_protobuf_envelopepb_extensions_proto_init() }
func file_github_com_dogmatiq_enginekit_protobuf_envelopepb_extensions_proto_init() {
	if File_github_com_dogmatiq_enginekit_protobuf_envelopepb_extensions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_enginekit_protobuf_envelopepb_extensions_proto_rawDesc), len(file_github_com_dogmatiq_enginekit_protobuf_envelopepb_extensions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_enginekit_protobuf_envelopepb_extensions_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_enginekit_protobuf_envelopepb_extensions_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_enginekit_protobuf_envelopepb_extensions_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_enginekit_protobuf_envelopepb_extensions_proto = out.File
	file_github_com_dogmatiq_enginekit_protobuf_envelopepb_extensions_proto_goTypes = nil
	file_github_com_dogmatiq_enginekit_protobuf_envelopepb_extensions_proto_depIdxs = nil
}
