// Code generated by protoc-gen-go-primo. DO NOT EDIT.
// versions:
// 	protoc-gen-go-primo v
// 	protoc              v6.30.2
// source: github.com/dogmatiq/enginekit/grpc/configgrpc/config.proto

package configgrpc

import (
	"context"
	configpb "github.com/dogmatiq/enginekit/protobuf/configpb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

type ListApplicationsRequestBuilder struct {
	prototype ListApplicationsRequest
}

// NewListApplicationsRequestBuilder returns a builder that constructs [ListApplicationsRequest] messages.
func NewListApplicationsRequestBuilder() *ListApplicationsRequestBuilder {
	return &ListApplicationsRequestBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *ListApplicationsRequestBuilder) From(x *ListApplicationsRequest) *ListApplicationsRequestBuilder {
	return b
}

// Build returns a new [ListApplicationsRequest] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *ListApplicationsRequestBuilder) Build() *ListApplicationsRequest {
	return &ListApplicationsRequest{}
}

type ListApplicationsResponseBuilder struct {
	prototype ListApplicationsResponse
}

// NewListApplicationsResponseBuilder returns a builder that constructs [ListApplicationsResponse] messages.
func NewListApplicationsResponseBuilder() *ListApplicationsResponseBuilder {
	return &ListApplicationsResponseBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *ListApplicationsResponseBuilder) From(x *ListApplicationsResponse) *ListApplicationsResponseBuilder {
	b.prototype.Applications = x.Applications
	return b
}

// Build returns a new [ListApplicationsResponse] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *ListApplicationsResponseBuilder) Build() *ListApplicationsResponse {
	return &ListApplicationsResponse{
		Applications: b.prototype.Applications,
	}
}

// WithApplications configures the builder to set the Applications field to v,
// then returns b.
func (b *ListApplicationsResponseBuilder) WithApplications(v []*configpb.Application) *ListApplicationsResponseBuilder {
	b.prototype.Applications = v
	return b
}

// ConfigAPIClientStub is a test implementation of the [ConfigAPIClient] interface.
var _ ConfigAPIClient = (*ConfigAPIClientStub)(nil)

type ConfigAPIClientStub struct {
	// ListApplicationsFunc is a function that implements the ListApplications RPC method.
	ListApplicationsFunc func(ctx context.Context, req *ListApplicationsRequest, options ...grpc.CallOption) (*ListApplicationsResponse, error)
}

// ListApplications calls c.ListApplicationsFunc if it is non-nil. Otherwise, it returns an error.
func (c *ConfigAPIClientStub) ListApplications(ctx context.Context, req *ListApplicationsRequest, options ...grpc.CallOption) (*ListApplicationsResponse, error) {
	if c.ListApplicationsFunc == nil {
		return nil, status.Error(codes.Unimplemented, "method ListApplications not implemented")
	}
	return c.ListApplicationsFunc(ctx, req, options...)
}

// SetApplications sets the x.Applications field to v, then returns x.
func (x *ListApplicationsResponse) SetApplications(v []*configpb.Application) {
	x.Applications = v
}
